INSERT INTO airbnb_units (city, country, host_id, n_bedrooms, n_beds, unit_id, unit_type)
VALUES ('Bruceville', 'worry', 1, 'occur', 'traditional', 1, 'threat',
('South Lukeborough', 'street', 2, 'start', 'almost', 2, 'election',
('Sherimouth', 'side', 3, 'sport', 'major', 3, 'between',
('East Heidi', 'age', 4, 'few', 'hear', 4, 'million',
('West George', 'receive', 5, 'forward', 'since', 5, 'general',
('North Christinebury', 'interest', 6, 'peace', 'avoid', 6, 'share',
('New Francesstad', 'read', 7, 'control', 'science', 7, 'manager',
('West Alexishaven', 'fear', 8, 'religious', 'end', 8, 'floor',
('Georgechester', 'side', 9, 'together', 'then', 9, 'customer',
('East Lawrenceburgh', 'represent', 10, 'student', 'participant', 10, 'modern',
('Greeneland', 'manage', 11, 'laugh', 'maybe', 11, 'not',
('Marcbury', 'water', 12, 'return', 'security', 12, 'it',
('Jenniferhaven', 'character', 13, 'improve', 'ever', 13, 'half',
('South Kristinehaven', 'modern', 14, 'off', 'professor', 14, 'benefit',
('North Caroline', 'star', 15, 'six', 'system', 15, 'song',
('Jamestown', 'there', 16, 'a', 'base', 16, 'attorney',
('West Davidfort', 'leader', 17, 'high', 'significant', 17, 'approach',
('East Conniemouth', 'cause', 18, 'watch', 'past', 18, 'compare',
('Margaretside', 'possible', 19, 'amount', 'over', 19, 'stage',
('Deborahport', 'scientist', 20, 'stuff', 'your', 20, 'development',
('Sarahaven', 'just', 21, 'rise', 'evidence', 21, 'order',
('Justinfurt', 'glass', 22, 'attack', 'thus', 22, 'apply',
('Wardburgh', 'information', 23, 'watch', 'war', 23, 'action',
('Port Laurenhaven', 'people', 24, 'catch', 'off', 24, 'director',
('North Wendy', 'hard', 25, 'above', 'current', 25, 'cultural',
('Lake Nicole', 'sign', 26, 'large', 'ever', 26, 'vote',
('South Beverly', 'probably', 27, 'team', 'adult', 27, 'son',
('West Chadberg', 'person', 28, 'try', 'decade', 28, 'act',
('Jonesburgh', 'act', 29, 'center', 'tonight', 29, 'fall',
('Bryanview', 'project', 30, 'appear', 'easy', 30, 'message',
('Stephaniebury', 'us', 31, 'reveal', 'company', 31, 'these',
('Port Natashastad', 'drug', 32, 'heavy', 'national', 32, 'development',
('East Elijahberg', 'attorney', 33, 'foot', 'assume', 33, 'charge',
('Deannamouth', 'their', 34, 'available', 'across', 34, 'interesting',
('Roseton', 'up', 35, 'offer', 'cold', 35, 'minute',
('Danielburgh', 'these', 36, 'system', 'authority', 36, 'while',
('North Kimstad', 'report', 37, 'day', 'budget', 37, 'believe',
('Angelbury', 'section', 38, 'investment', 'idea', 38, 'daughter',
('New Roberthaven', 'someone', 39, 'national', 'outside', 39, 'two',
('East Veronica', 'character', 40, 'return', 'upon', 40, 'shake',
('Chrisbury', 'hand', 41, 'social', 'place', 41, 'tough',
('Booneland', 'safe', 42, 'group', 'spring', 42, 'clear',
('Lake Codyhaven', 'understand', 43, 'affect', 'discuss', 43, 'trouble',
('New Laura', 'of', 44, 'rest', 'able', 44, 'capital',
('New Christopher', 'health', 45, 'people', 'people', 45, 'boy',
('North Jerry', 'school', 46, 'tell', 'word', 46, 'let',
('Cruzside', 'increase', 47, 'executive', 'majority', 47, 'usually',
('South Justin', 'center', 48, 'organization', 'guy', 48, 'surface',
('Martinton', 'trouble', 49, 'agency', 'can', 49, 'keep',
('Port Lauren', 'any', 50, 'nearly', 'alone', 50, 'however',
('Deanstad', 'dog', 51, 'child', 'compare', 51, 'interview',
('Mitchellhaven', 'exactly', 52, 'experience', 'clear', 52, 'our',
('Susanview', 'person', 53, 'world', 'pay', 53, 'television',
('Dawnbury', 'size', 54, 'season', 'question', 54, 'front',
('South Mariechester', 'interest', 55, 'onto', 'try', 55, 'type',
('Brandistad', 'open', 56, 'fire', 'serve', 56, 'final',
('Julieview', 'executive', 57, 'among', 'now', 57, 'skill',
('Gailland', 'beyond', 58, 'there', 'sometimes', 58, 'agent',
('North Kevin', 'goal', 59, 'recognize', 'right', 59, 'least',
('North Jeffreyburgh', 'natural', 60, 'us', 'hotel', 60, 'voice',
('Lake Katherine', 'outside', 61, 'call', 'usually', 61, 'lawyer',
('Russoport', 'find', 62, 'arrive', 'various', 62, 'relationship',
('South Timothyshire', 'worker', 63, 'field', 'economy', 63, 'guess',
('Dianahaven', 'home', 64, 'star', 'world', 64, 'share',
('Katiehaven', 'easy', 65, 'director', 'star', 65, 'space',
('New Davidhaven', 'six', 66, 'yet', 'similar', 66, 'easy',
('Lake Anna', 'decide', 67, 'challenge', 'name', 67, 'model',
('Port Zachary', 'magazine', 68, 'now', 'range', 68, 'dinner',
('Harrisonberg', 'walk', 69, 'local', 'tough', 69, 'administration',
('Johnfurt', 'represent', 70, 'join', 'fine', 70, 'argue',
('South Davidside', 'operation', 71, 'office', 'customer', 71, 'doctor',
('Robertchester', 'wife', 72, 'weight', 'establish', 72, 'court',
('Port Emily', 'amount', 73, 'tough', 'important', 73, 'vote',
('Lake Austin', 'state', 74, 'media', 'floor', 74, 'out',
('East Christophermouth', 'church', 75, 'population', 'space', 75, 'blood',
('Natalieport', 'past', 76, 'and', 'medical', 76, 'religious',
('New Melanie', 'hand', 77, 'indeed', 'party', 77, 'account',
('Port Christopherton', 'thank', 78, 'citizen', 'sea', 78, 'artist',
('Shannonchester', 'but', 79, 'course', 'dream', 79, 'development',
('Christopherside', 'learn', 80, 'nothing', 'Congress', 80, 'type',
('West Paulmouth', 'response', 81, 'understand', 'building', 81, 'oil',
('Kimberlystad', 'artist', 82, 'beyond', 'least', 82, 'western',
('Alexisshire', 'those', 83, 'prevent', 'despite', 83, 'even',
('East Phyllismouth', 'far', 84, 'figure', 'toward', 84, 'particular',
('Shermanview', 'study', 85, 'finish', 'wish', 85, 'assume',
('Melissahaven', 'view', 86, 'should', 'think', 86, 'what',
('South Monica', 'by', 87, 'second', 'world', 87, 'wife',
('East Sandra', 'water', 88, 'everything', 'strong', 88, 'probably',
('East Craig', 'project', 89, 'significant', 'check', 89, 'become',
('Carolynmouth', 'office', 90, 'design', 'sea', 90, 'firm',
('Jeffreychester', 'wait', 91, 'join', 'benefit', 91, 'student',
('East Vanessaburgh', 'protect', 92, 'sign', 'miss', 92, 'general',
('Jamesberg', 'professional', 93, 'power', 'station', 93, 'recognize',
('Wattsfort', 'both', 94, 'writer', 'work', 94, 'already',
('West Jonathanmouth', 'science', 95, 'medical', 'environmental', 95, 'design',
('Melissaport', 'somebody', 96, 'student', 'enough', 96, 'shoulder',
('Kramertown', 'build', 97, 'Congress', 'present', 97, 'serious',
('Jacksonmouth', 'house', 98, 'five', 'race', 98, 'their',
('Francesmouth', 'travel', 99, 'know', 'what', 99, 'economic',
('West Jacqueline', 'likely', 100, 'without', 'those', 100, 'something',
('Washingtonhaven', 'wife', 101, 'heavy', 'ability', 101, 'skin',
('West Frederick', 'many', 102, 'focus', 'effect', 102, 'wife',
('West Tiffanytown', 'do', 103, 'check', 'explain', 103, 'question',
('Bryanview', 'wind', 104, 'keep', 'all', 104, 'option',
('Lake Andrewbury', 'yourself', 105, 'thus', 'million', 105, 'north',
('Maryton', 'star', 106, 'bill', 'particularly', 106, 'red',
('Lake Joseph', 'key', 107, 'close', 'can', 107, 'travel',
('South Jennifermouth', 'Mrs', 108, 'paper', 'tough', 108, 'truth',
('Tracyside', 'ready', 109, 'last', 'center', 109, 'thousand',
('Allenchester', 'already', 110, 'behind', 'not', 110, 'assume',
('Henryburgh', 'buy', 111, 'paper', 'several', 111, 'necessary',
('Berrychester', 'significant', 112, 'sort', 'rich', 112, 'even',
('Kathleenmouth', 'in', 113, 'partner', 'school', 113, 'expert',
('North Maxwellland', 'how', 114, 'development', 'exist', 114, 'ability',
('East Maryborough', 'education', 115, 'party', 'themselves', 115, 'bill',
('Adamsview', 'cause', 116, 'power', 'happen', 116, 'culture',
('Hughesburgh', 'once', 117, 'size', 'experience', 117, 'among',
('Perezburgh', 'good', 118, 'live', 'wife', 118, 'get',
('South Cheryl', 'social', 119, 'institution', 'necessary', 119, 'eight',
('New Matthewport', 'short', 120, 'fact', 'wait', 120, 'teach',
('East Jesse', 'series', 121, 'model', 'report', 121, 'election',
('Meganfurt', 'dark', 122, 'half', 'very', 122, 'morning',
('Cannonborough', 'reason', 123, 'table', 'read', 123, 'everything',
('Gutierrezland', 'son', 124, 'sport', 'whose', 124, 'agency',
('Port Frank', 'lot', 125, 'mention', 'scene', 125, 'well',
('Victoriamouth', 'factor', 126, 'understand', 'young', 126, 'fill',
('Wallacechester', 'down', 127, 'staff', 'myself', 127, 'there',
('Ashleyburgh', 'painting', 128, 'author', 'situation', 128, 'cold',
('Matthewmouth', 'appear', 129, 'would', 'sea', 129, 'official',
('North Jordanmouth', 'like', 130, 'hospital', 'industry', 130, 'feeling',
('Michelleview', 'other', 131, 'month', 'although', 131, 'bed',
('North Kimfort', 'ahead', 132, 'baby', 'number', 132, 'might',
('Dawnbury', 'television', 133, 'sea', 'responsibility', 133, 'test',
('New Stevenborough', 'step', 134, 'her', 'agreement', 134, 'statement',
('Lake Melanie', 'describe', 135, 'trip', 'head', 135, 'quite',
('Janetfurt', 'yard', 136, 'service', 'down', 136, 'student',
('North Kimberlytown', 'north', 137, 'ready', 'evidence', 137, 'partner',
('Dawnstad', 'style', 138, 'fire', 'perform', 138, 'perhaps',
('North Sylvia', 'owner', 139, 'down', 'represent', 139, 'glass',
('Austinmouth', 'attention', 140, 'beyond', 'involve', 140, 'guess',
('West Jonathanport', 'child', 141, 'man', 'section', 141, 'official',
('New Crystal', 'set', 142, 'just', 'there', 142, 'space',
('Grantside', 'card', 143, 'budget', 'responsibility', 143, 'force',
('Michaelview', 'health', 144, 'market', 'run', 144, 'put',
('Norrisberg', 'air', 145, 'citizen', 'author', 145, 'whether',
('Thompsonmouth', 'trouble', 146, 'wrong', 'organization', 146, 'page',
('New Jake', 'develop', 147, 'tonight', 'ever', 147, 'probably',
('Carpenterchester', 'safe', 148, 'born', 'while', 148, 'data',
('Mackport', 'box', 149, 'live', 'food', 149, 'reality',
('New Phillipbury', 'which', 150, 'remember', 'father', 150, 'onto',
('Owensstad', 'soldier', 151, 'along', 'prepare', 151, 'drug',
('Port Josephberg', 'international', 152, 'myself', 'term', 152, 'probably',
('South Sarahberg', 'same', 153, 'require', 'family', 153, 'minute',
('Ricefurt', 'American', 154, 'set', 'these', 154, 'indicate',
('North Larry', 'paper', 155, 'admit', 'produce', 155, 'society',
('Bobbyton', 'process', 156, 'practice', 'understand', 156, 'next',
('New Adrian', 'exactly', 157, 'buy', 'yet', 157, 'bag',
('Norrismouth', 'it', 158, 'feel', 'avoid', 158, 'rate',
('East Denise', 'ok', 159, 'somebody', 'campaign', 159, 'people',
('Macdonaldshire', 'American', 160, 'rich', 'something', 160, 'task',
('Matthewville', 'around', 161, 'soon', 'campaign', 161, 'wear',
('North Aaron', 'region', 162, 'and', 'note', 162, 'defense',
('Port Bradyville', 'suffer', 163, 'everyone', 'on', 163, 'bill',
('North Lisa', 'phone', 164, 'under', 'administration', 164, 'center',
('Karenport', 'operation', 165, 'seat', 'claim', 165, 'she',
('Smithland', 'evidence', 166, 'make', 'scientist', 166, 'big',
('Whiteville', 'collection', 167, 'protect', 'however', 167, 'a',
('East Tammy', 'industry', 168, 'table', 'customer', 168, 'media',
('East Angelafort', 'wear', 169, 'or', 'drop', 169, 'character',
('Lake Kristin', 'structure', 170, 'itself', 'pay', 170, 'week',
('South Brandon', 'industry', 171, 'charge', 'debate', 171, 'Congress',
('Kevinburgh', 'admit', 172, 'then', 'mean', 172, 'evening',
('Harrischester', 'design', 173, 'level', 'agency', 173, 'remain',
('Starkberg', 'national', 174, 'thing', 'particular', 174, 'thing',
('South Gary', 'capital', 175, 'girl', 'whom', 175, 'live',
('Lake Raymondfort', 'rule', 176, 'street', 'where', 176, 'hot',
('Sanchezbury', 'school', 177, 'crime', 'probably', 177, 'process',
('Donaldbury', 'for', 178, 'moment', 'air', 178, 'particularly',
('West Bradley', 'fall', 179, 'especially', 'blood', 179, 'pressure',
('North Michelle', 'every', 180, 'report', 'sure', 180, 'campaign',
('New Michaelburgh', 'successful', 181, 'check', 'enough', 181, 'crime',
('South Alexander', 'out', 182, 'try', 'sing', 182, 'environment',
('Nathantown', 'trial', 183, 'inside', 'ready', 183, 'cost',
('Hudsonburgh', 'program', 184, 'real', 'up', 184, 'approach',
('North Anne', 'project', 185, 'center', 'brother', 185, 'drive',
('New Miguelside', 'think', 186, 'even', 'day', 186, 'program',
('Penningtonborough', 'address', 187, 'reflect', 'media', 187, 'either',
('South Isaacton', 'lawyer', 188, 'account', 'rise', 188, 'property',
('Mossmouth', 'magazine', 189, 'success', 'Mr', 189, 'world',
('North Mariofort', 'public', 190, 'kitchen', 'else', 190, 'night',
('Mackland', 'usually', 191, 'although', 'science', 191, 'read',
('Lake Austinview', 'PM', 192, 'future', 'food', 192, 'only',
('Hunterville', 'water', 193, 'learn', 'system', 193, 'indicate',
('New Tina', 'indicate', 194, 'draw', 'chair', 194, 'theory',
('South Gailview', 'require', 195, 'safe', 'important', 195, 'art',
('South Dennis', 'good', 196, 'standard', 'rich', 196, 'road',
('Smithtown', 'majority', 197, 'collection', 'history', 197, 'but',
('New Melanieton', 'result', 198, 'interest', 'type', 198, 'today',
('New Kellymouth', 'religious', 199, 'lay', 'so', 199, 'and',
('Smithburgh', 'floor', 200, 'paper', 'available', 200, 'everyone',
('Georgeshire', 'western', 201, 'during', 'party', 201, 'local',
('East Brianna', 'employee', 202, 'need', 'interview', 202, 'chance',
('Port Gary', 'speech', 203, 'live', 'national', 203, 'air',
('North Michelle', 'across', 204, 'might', 'give', 204, 'physical',
('Reidberg', 'table', 205, 'through', 'attack', 205, 'cost',
('West Randyport', 'really', 206, 'baby', 'test', 206, 'system',
('Prestonton', 'reality', 207, 'current', 'case', 207, 'save',
('Mcdowellmouth', 'professional', 208, 'student', 'sing', 208, 'type',
('Henryville', 'various', 209, 'three', 'conference', 209, 'without',
('New Ericaborough', 'future', 210, 'computer', 'outside', 210, 'poor',
('Kristiberg', 'peace', 211, 'white', 'both', 211, 'seven',
('North Craig', 'population', 212, 'understand', 'partner', 212, 'out',
('East Cassandramouth', 'feeling', 213, 'force', 'mouth', 213, 'through',
('New Jessica', 'leg', 214, 'yard', 'perform', 214, 'sea',
('Phamburgh', 'pattern', 215, 'market', 'process', 215, 'both',
('South Amandachester', 'care', 216, 'after', 'radio', 216, 'opportunity',
('South Carl', 'usually', 217, 'science', 'at', 217, 'cell',
('New Todd', 'turn', 218, 'region', 'commercial', 218, 'because',
('South Garyhaven', 'professional', 219, 'collection', 'together', 219, 'mean',
('Bakertown', 'actually', 220, 'prevent', 'doctor', 220, 'all',
('Johnsonshire', 'player', 221, 'letter', 'begin', 221, 'something',
('Alexisborough', 'from', 222, 'television', 'will', 222, 'above',
('Port Sarahstad', 'blood', 223, 'concern', 'series', 223, 'art',
('Collinsstad', 'back', 224, 'especially', 'until', 224, 'generation',
('Oliviaville', 'lawyer', 225, 'area', 'series', 225, 'pick',
('Hoganland', 'picture', 226, 'order', 'smile', 226, 'floor',
('New Susan', 'word', 227, 'candidate', 'daughter', 227, 'help',
('Meghanbury', 'carry', 228, 'offer', 'would', 228, 'just',
('Bakerberg', 'paper', 229, 'himself', 'feel', 229, 'heart',
('Lake Scottland', 'bad', 230, 'field', 'stock', 230, 'stage',
('Dorseyhaven', 'first', 231, 'without', 'either', 231, 'work',
('Nelsonmouth', 'different', 232, 'investment', 'red', 232, 'own',
('Taylorborough', 'common', 233, 'than', 'role', 233, 'nice',
('Haynesborough', 'time', 234, 'help', 'month', 234, 'bag',
('Markville', 'next', 235, 'entire', 'process', 235, 'life',
('North Coreyshire', 'quickly', 236, 'civil', 'media', 236, 'catch',
('Lake Amyland', 'single', 237, 'range', 'far', 237, 'understand',
('Port Daniel', 'institution', 238, 'without', 'prove', 238, 'type',
('Thompsonview', 'smile', 239, 'project', 'player', 239, 'wife',
('Marytown', 'local', 240, 'season', 'song', 240, 'pay',
('Zacharyland', 'side', 241, 'mouth', 'everybody', 241, 'officer',
('South Beckyshire', 'along', 242, 'hair', 'example', 242, 'job',
('Hodgeview', 'above', 243, 'stage', 'including', 243, 'question',
('Henryview', 'evening', 244, 'sound', 'section', 244, 'wife',
('Gallowayborough', 'rule', 245, 'glass', 'church', 245, 'fine',
('Port Corey', 'agreement', 246, 'line', 'book', 246, 'bring',
('Gardnerville', 'right', 247, 'culture', 'garden', 247, 'tough',
('East Mark', 'recent', 248, 'democratic', 'realize', 248, 'medical',
('Lake Kimberly', 'director', 249, 'bank', 'network', 249, 'dream',
('New Markland', 'trade', 250, 'western', 'child', 250, 'would',
('Leefort', 'condition', 251, 'avoid', 'because', 251, 'produce',
('Cruzmouth', 'first', 252, 'attack', 'their', 252, 'civil',
('North Charles', 'your', 253, 'shoulder', 'water', 253, 'hair',
('Wheelerton', 'walk', 254, 'record', 'family', 254, 'two',
('Amandamouth', 'senior', 255, 'old', 'senior', 255, 'everybody',
('West Jeff', 'executive', 256, 'reason', 'fill', 256, 'American',
('Christieview', 'natural', 257, 'pretty', 'exactly', 257, 'say',
('Matthewland', 'organization', 258, 'first', 'answer', 258, 'fund',
('Sherrimouth', 'he', 259, 'those', 'practice', 259, 'for',
('Lake John', 'radio', 260, 'painting', 'tax', 260, 'business',
('Powellfurt', 'often', 261, 'music', 'in', 261, 'dark',
('Riverahaven', 'religious', 262, 'appear', 'gun', 262, 'go',
('South Madisonbury', 'college', 263, 'fire', 'environment', 263, 'appear',
('Joshuaside', 'forward', 264, 'quite', 'meeting', 264, 'despite',
('Holmesside', 'study', 265, 'answer', 'truth', 265, 'financial',
('Kevinport', 'future', 266, 'be', 'imagine', 266, 'build',
('Port Kennethview', 'fine', 267, 'describe', 'amount', 267, 'natural',
('South Jonathanton', 'media', 268, 'mention', 'pull', 268, 'that',
('East Debraton', 'whom', 269, 'performance', 'turn', 269, 'like',
('Daltonland', 'word', 270, 'strategy', 'whole', 270, 'building',
('Carlystad', 'lay', 271, 'enjoy', 'sure', 271, 'movie',
('North Ryanmouth', 'easy', 272, 'believe', 'just', 272, 'partner',
('Cookton', 'receive', 273, 'ever', 'church', 273, 'seem',
('New Stacey', 'attorney', 274, 'watch', 'any', 274, 'conference',
('North Gregorytown', 'best', 275, 'when', 'condition', 275, 'open',
('Wilkinsstad', 'cultural', 276, 'evidence', 'lot', 276, 'administration',
('Williestad', 'above', 277, 'rest', 'along', 277, 'its',
('North Angelachester', 'clear', 278, 'either', 'fund', 278, 'thousand',
('Tylerhaven', 'consumer', 279, 'wrong', 'trip', 279, 'factor',
('West Charlesmouth', 'never', 280, 'whole', 'student', 280, 'play',
('Donnaville', 'keep', 281, 'should', 'forget', 281, 'glass',
('Heathport', 'senior', 282, 'I', 'media', 282, 'lawyer',
('Paulachester', 'effort', 283, 'player', 'ahead', 283, 'guy',
('East Jacob', 'seem', 284, 'walk', 'eye', 284, 'necessary',
('Markfurt', 'wish', 285, 'cultural', 'significant', 285, 'player',
('Steveton', 'design', 286, 'say', 'body', 286, 'whom',
('Josephhaven', 'each', 287, 'these', 'cold', 287, 'industry',
('Lake Richard', 'not', 288, 'condition', 'phone', 288, 'same',
('Jacobtown', 'cultural', 289, 'action', 'democratic', 289, 'not',
('West Kellyfort', 'key', 290, 'any', 'ground', 290, 'federal',
('Rachelbury', 'left', 291, 'true', 'style', 291, 'standard',
('New Adammouth', 'media', 292, 'imagine', 'floor', 292, 'save',
('New Kenneth', 'agreement', 293, 'certainly', 'face', 293, 'participant',
('North Jennifer', 'significant', 294, 'value', 'risk', 294, 'provide',
('South Benjamin', 'child', 295, 'drop', 'lay', 295, 'former',
('Juliatown', 'measure', 296, 'go', 'wrong', 296, 'begin',
('South Jeremy', 'statement', 297, 'fill', 'cultural', 297, 'popular',
('West Thomas', 'strong', 298, 'recently', 'hope', 298, 'anyone',
('Port Jackfurt', 'west', 299, 'share', 'reduce', 299, 'wall',
('North Rachel', 'throughout', 300, 'deal', 'less', 300, 'cultural');