INSERT INTO airbnb_apartments (apartment_id, apartment_type, city, country, host_id, n_bedrooms, n_beds)
VALUES (1, 'floor', 'South Carrie', 'president', 1, 'possible', 'movement',
(2, 'community', 'East Christopher', 'act', 2, 'many', 'position',
(3, 'recognize', 'Williamsborough', 'difficult', 3, 'notice', 'marriage',
(4, 'too', 'Alisonbury', 'card', 4, 'of', 'particular',
(5, 'technology', 'Lake Scotttown', 'heart', 5, 'war', 'out',
(6, 'bit', 'Lake Clairehaven', 'deep', 6, 'yes', 'order',
(7, 'early', 'Fischerville', 'leave', 7, 'activity', 'account',
(8, 'reality', 'Lewisstad', 'common', 8, 'local', 'local',
(9, 'help', 'Jenniferfurt', 'night', 9, 'form', 'maybe',
(10, 'word', 'West Gavinmouth', 'stop', 10, 'your', 'theory',
(11, 'if', 'New Jeffreyberg', 'worry', 11, 'staff', 'whole',
(12, 'ready', 'Port Scottborough', 'develop', 12, 'particular', 'evening',
(13, 'on', 'Lake Lisa', 'everyone', 13, 'officer', 'huge',
(14, 'black', 'Hughesview', 'share', 14, 'speak', 'security',
(15, 'power', 'South Brad', 'act', 15, 'all', 'year',
(16, 'red', 'Lake Ian', 'lose', 16, 'community', 'thus',
(17, 'wish', 'South Zachary', 'boy', 17, 'it', 'list',
(18, 'music', 'Wilsonborough', 'cut', 18, 'southern', 'speak',
(19, 'increase', 'Ramirezville', 'relate', 19, 'system', 'second',
(20, 'news', 'Johnnyton', 'air', 20, 'environment', 'growth',
(21, 'memory', 'Lake Charlesburgh', 'long', 21, 'water', 'exist',
(22, 'cold', 'Transhire', 'bring', 22, 'low', 'according',
(23, 'tend', 'Theresafort', 'threat', 23, 'wall', 'if',
(24, 'class', 'Hoganhaven', 'on', 24, 'dark', 'become',
(25, 'foreign', 'Larsonland', 'billion', 25, 'budget', 'summer',
(26, 'executive', 'East Jerry', 'tell', 26, 'suddenly', 'pattern',
(27, 'set', 'South Theresaberg', 'process', 27, 'method', 'ten',
(28, 'available', 'Carrollberg', 'finish', 28, 'how', 'to',
(29, 'however', 'Port Crystaltown', 'if', 29, 'back', 'off',
(30, 'pattern', 'Andersonton', 'any', 30, 'attention', 'type',
(31, 'whole', 'Lake Heather', 'mother', 31, 'trouble', 'perform',
(32, 'measure', 'Daviesview', 'may', 32, 'in', 'international',
(33, 'prevent', 'Monicaland', 'business', 33, 'nature', 'behavior',
(34, 'claim', 'East Jonathan', 'expert', 34, 'mother', 'special',
(35, 'kid', 'North Stephanie', 'not', 35, 'rock', 'energy',
(36, 'throw', 'South Tamifort', 'direction', 36, 'rich', 'sea',
(37, 'memory', 'Alisontown', 'cost', 37, 'Mr', 'author',
(38, 'admit', 'East Jonathan', 'technology', 38, 'plant', 'fact',
(39, 'government', 'Wademouth', 'learn', 39, 'population', 'nearly',
(40, 'several', 'Lake Anneborough', 'civil', 40, 'world', 'make',
(41, 'team', 'Johnsberg', 'interesting', 41, 'social', 'billion',
(42, 'form', 'Jamesview', 'easy', 42, 'bring', 'these',
(43, 'direction', 'Morrisstad', 'summer', 43, 'option', 'animal',
(44, 'always', 'West Patriciaborough', 'book', 44, 'nature', 'another',
(45, 'partner', 'Andersonmouth', 'industry', 45, 'sport', 'think',
(46, 'long', 'Amybury', 'data', 46, 'important', 'poor',
(47, 'art', 'Kyleport', 'read', 47, 'morning', 'become',
(48, 'skill', 'Allenfort', 'performance', 48, 'commercial', 'leader',
(49, 'card', 'Jasonhaven', 'her', 49, 'no', 'born',
(50, 'note', 'Jennaland', 'western', 50, 'responsibility', 'student',
(51, 'put', 'Lake Sydneymouth', 'leg', 51, 'court', 'evidence',
(52, 'wind', 'Velezmouth', 'figure', 52, 'receive', 'though',
(53, 'identify', 'South Lucas', 'game', 53, 'network', 'include',
(54, 'begin', 'Lindabury', 'everybody', 54, 'yeah', 'rise',
(55, 'including', 'East Eric', 'because', 55, 'TV', 'part',
(56, 'weight', 'Port Jacquelineborough', 'little', 56, 'administration', 'media',
(57, 'big', 'Ashleyview', 'sort', 57, 'course', 'believe',
(58, 'population', 'Lake Jamie', 'seven', 58, 'mission', 'customer',
(59, 'specific', 'Joshuaberg', 'pass', 59, 'whom', 'source',
(60, 'trip', 'Robertburgh', 'expect', 60, 'husband', 'I',
(61, 'head', 'North Ashley', 'chance', 61, 'style', 'budget',
(62, 'case', 'Lake Tylerfurt', 'leave', 62, 'probably', 'ten',
(63, 'she', 'Nancyport', 'stop', 63, 'despite', 'better',
(64, 'any', 'Owensfurt', 'movement', 64, 'system', 'trade',
(65, 'there', 'New Samanthaville', 'strategy', 65, 'break', 'police',
(66, 'final', 'Port Joshua', 'program', 66, 'position', 'day',
(67, 'girl', 'Stevenhaven', 'size', 67, 'oil', 'message',
(68, 'avoid', 'Blackwellhaven', 'suggest', 68, 'sell', 'system',
(69, 'star', 'North Gregoryside', 'dream', 69, 'this', 'report',
(70, 'cultural', 'South Ronaldview', 'street', 70, 'environment', 'education',
(71, 'less', 'Donnaberg', 'factor', 71, 'treatment', 'lawyer',
(72, 'stuff', 'Simmonsstad', 'similar', 72, 'media', 'strong',
(73, 'structure', 'Timothystad', 'better', 73, 'back', 'evening',
(74, 'word', 'East Isabelshire', 'suggest', 74, 'direction', 'report',
(75, 'film', 'Thompsonton', 'sell', 75, 'evidence', 'beyond',
(76, 'garden', 'North John', 'result', 76, 'often', 'no',
(77, 'tonight', 'Liview', 'continue', 77, 'man', 'situation',
(78, 'stand', 'Shariton', 'oil', 78, 'administration', 'test',
(79, 'poor', 'South Nathanfurt', 'interesting', 79, 'visit', 'bar',
(80, 'common', 'West Danielmouth', 'discussion', 80, 'third', 'because',
(81, 'family', 'Michaelton', 'others', 81, 'street', 'specific',
(82, 'quite', 'Brownshire', 'inside', 82, 'magazine', 'reason',
(83, 'see', 'Lake Willie', 'husband', 83, 'finish', 'TV',
(84, 'fall', 'Josephstad', 'approach', 84, 'cut', 'success',
(85, 'maintain', 'West Robyn', 'build', 85, 'low', 'southern',
(86, 'quite', 'Leeville', 'view', 86, 'myself', 'performance',
(87, 'mother', 'West Dianemouth', 'natural', 87, 'manager', 'history',
(88, 'phone', 'Silvafurt', 'and', 88, 'finally', 'blue',
(89, 'kitchen', 'Pettystad', 'way', 89, 'particular', 'around',
(90, 'such', 'Buchananbury', 'job', 90, 'for', 'throw',
(91, 'their', 'East Connorbury', 'coach', 91, 'a', 'positive',
(92, 'put', 'West Kathrynton', 'ball', 92, 'around', 'strategy',
(93, 'wall', 'Port Robertton', 'he', 93, 'keep', 'interesting',
(94, 'paper', 'Christinaberg', 'young', 94, 'month', 'there',
(95, 'after', 'New Lisa', 'cell', 95, 'week', 'anything',
(96, 'since', 'Fieldsburgh', 'carry', 96, 'operation', 'hot',
(97, 'far', 'Brianstad', 'wind', 97, 'run', 'break',
(98, 'surface', 'Jenniferton', 'indeed', 98, 'enter', 'less',
(99, 'energy', 'North Russellville', 'significant', 99, 'may', 'themselves',
(100, 'huge', 'Port Shannon', 'different', 100, 'citizen', 'tree',
(101, 'rich', 'West Hector', 'miss', 101, 'mention', 'car',
(102, 'little', 'Brandonville', 'most', 102, 'management', 'nice',
(103, 'send', 'South Amanda', 'tonight', 103, 'pay', 'war',
(104, 'especially', 'South Andrewfurt', 'enough', 104, 'hotel', 'send',
(105, 'serve', 'Russellmouth', 'scientist', 105, 'time', 'floor',
(106, 'region', 'Kellyville', 'style', 106, 'black', 'thing',
(107, 'pull', 'East Heathershire', 'amount', 107, 'me', 'land',
(108, 'policy', 'South Joshuaville', 'fall', 108, 'tell', 'future',
(109, 'kid', 'Lake Angelastad', 'middle', 109, 'my', 'understand',
(110, 'artist', 'Port Stephanie', 'ready', 110, 'large', 'team',
(111, 'social', 'Georgebury', 'Democrat', 111, 'young', 'great',
(112, 'oil', 'Lake Richardland', 'beat', 112, 'include', 'describe',
(113, 'production', 'New Elizabethshire', 'party', 113, 'against', 'heart',
(114, 'so', 'Walkerfort', 'direction', 114, 'weight', 'laugh',
(115, 'whom', 'Wrightfurt', 'even', 115, 'young', 'upon',
(116, 'change', 'East Megan', 'world', 116, 'seek', 'two',
(117, 'step', 'Jamieberg', 'practice', 117, 'seven', 'nature',
(118, 'strategy', 'Port Guyshire', 'year', 118, 'nature', 'if',
(119, 'and', 'East Caleb', 'animal', 119, 'bed', 'way',
(120, 'conference', 'South Gabrielborough', 'in', 120, 'agreement', 'face',
(121, 'allow', 'Andreaberg', 'star', 121, 'bank', 'decision',
(122, 'draw', 'Port Joshuamouth', 'see', 122, 'power', 'Republican',
(123, 'owner', 'North Jillton', 'ability', 123, 'current', 'dark',
(124, 'born', 'Port Meredith', 'part', 124, 'early', 'air',
(125, 'their', 'Boydburgh', 'live', 125, 'international', 'these',
(126, 'change', 'North Lacey', 'dream', 126, 'reduce', 'Republican',
(127, 'seek', 'Sullivanview', 'join', 127, 'artist', 'choice',
(128, 'before', 'Russoville', 'fire', 128, 'he', 'adult',
(129, 'course', 'Piercechester', 'no', 129, 'cut', 'both',
(130, 'table', 'Kathrynberg', 'everything', 130, 'best', 'affect',
(131, 'every', 'South Stephenberg', 'themselves', 131, 'international', 'five',
(132, 'last', 'Rodriguezbury', 'near', 132, 'themselves', 'seven',
(133, 'approach', 'Flowersland', 'company', 133, 'chair', 'check',
(134, 'court', 'Hodgesstad', 'list', 134, 'those', 'really',
(135, 'scene', 'Leehaven', 'memory', 135, 'next', 'address',
(136, 'agreement', 'Stevenberg', 'impact', 136, 'hospital', 'far',
(137, 'establish', 'Johnsonland', 'question', 137, 'wish', 'recent',
(138, 'question', 'New Annemouth', 'it', 138, 'age', 'serious',
(139, 'home', 'Huffshire', 'relationship', 139, 'entire', 'year',
(140, 'door', 'Port Joshua', 'move', 140, 'position', 'order',
(141, 'be', 'Markfurt', 'per', 141, 'huge', 'add',
(142, 'north', 'South Nicole', 'effort', 142, 'course', 'pattern',
(143, 'somebody', 'Solisburgh', 'concern', 143, 'realize', 'top',
(144, 'team', 'Michaelville', 'too', 144, 'tell', 'simply',
(145, 'watch', 'Hollowayview', 'performance', 145, 'father', 'themselves',
(146, 'enough', 'Lake Kevinside', 'alone', 146, 'plant', 'away',
(147, 'people', 'Mccormickstad', 'leg', 147, 'smile', 'decide',
(148, 'blue', 'East Gregoryton', 'design', 148, 'number', 'pattern',
(149, 'show', 'West Claudiafurt', 'hope', 149, 'unit', 'soon',
(150, 'read', 'Lake Jeffreyport', 'practice', 150, 'debate', 'office',
(151, 'husband', 'New Gabriel', 'now', 151, 'director', 'should',
(152, 'question', 'Michaelhaven', 'necessary', 152, 'happen', 'account',
(153, 'beat', 'Lake Kathrynberg', 'organization', 153, 'born', 'place',
(154, 'season', 'East Toddland', 'model', 154, 'several', 'believe',
(155, 'west', 'New Nathanborough', 'statement', 155, 'it', 'old',
(156, 'pattern', 'Crossbury', 'not', 156, 'wall', 'almost',
(157, 'game', 'Robinburgh', 'with', 157, 'sit', 'go',
(158, 'drive', 'Port Rebecca', 'mind', 158, 'cultural', 'suggest',
(159, 'teach', 'Port Elizabethbury', 'box', 159, 'former', 'vote',
(160, 'go', 'South Bobby', 'coach', 160, 'hundred', 'something',
(161, 'successful', 'Matthewborough', 'Congress', 161, 'with', 'care',
(162, 'idea', 'Jenkinsberg', 'mention', 162, 'land', 'bag',
(163, 'there', 'Daviston', 'special', 163, 'despite', 'majority',
(164, 'management', 'Gomeztown', 'position', 164, 'recently', 'energy',
(165, 'like', 'Brianton', 'wife', 165, 'no', 'conference',
(166, 'woman', 'Youngbury', 'training', 166, 'whether', 'language',
(167, 'scientist', 'Aliciamouth', 'somebody', 167, 'feel', 'baby',
(168, 'trade', 'South Bryce', 'order', 168, 'hope', 'story',
(169, 'evening', 'Port Joelview', 'leader', 169, 'especially', 'write',
(170, 'body', 'South Williamville', 'method', 170, 'young', 'finish',
(171, 'color', 'North Wandaside', 'together', 171, 'try', 'care',
(172, 'store', 'Christopherbury', 'relationship', 172, 'third', 'light',
(173, 'American', 'Lake Garychester', 'official', 173, 'affect', 'according',
(174, 'loss', 'Lake Markland', 'speech', 174, 'far', 'read',
(175, 'attention', 'Port Stephanieborough', 'baby', 175, 'meet', 'into',
(176, 'develop', 'Wendystad', 'customer', 176, 'game', 'during',
(177, 'race', 'Dawnview', 'nothing', 177, 'full', 'smile',
(178, 'few', 'North Jillian', 'show', 178, 'cultural', 'here',
(179, 'significant', 'North Brenda', 'item', 179, 'create', 'nothing',
(180, 'party', 'Lake Lynnbury', 'clearly', 180, 'popular', 'picture',
(181, 'score', 'Millertown', 'after', 181, 'price', 'attention',
(182, 'their', 'Osborneborough', 'sit', 182, 'wide', 'church',
(183, 'summer', 'Robertfort', 'central', 183, 'change', 'woman',
(184, 'share', 'Holdenmouth', 'director', 184, 'identify', 'race',
(185, 'TV', 'South Gabriel', 'seek', 185, 'end', 'black',
(186, 'early', 'South Christopher', 'age', 186, 'responsibility', 'though',
(187, 'tell', 'Lake Kimberlyshire', 'cut', 187, 'open', 'produce',
(188, 'form', 'Pamelatown', 'well', 188, 'finally', 'rule',
(189, 'image', 'Myersview', 'interest', 189, 'any', 'article',
(190, 'imagine', 'Crystalfort', 'area', 190, 'center', 'notice',
(191, 'happy', 'Hullmouth', 'sister', 191, 'Republican', 'difference',
(192, 'organization', 'Lake Crystal', 'the', 192, 'tend', 'message',
(193, 'energy', 'New Mark', 'laugh', 193, 'win', 'view',
(194, 'raise', 'East Caitlin', 'production', 194, 'last', 'act',
(195, 'out', 'North Mistyfort', 'seat', 195, 'example', 'cut',
(196, 'evening', 'Jessicaland', 'serious', 196, 'necessary', 'sing',
(197, 'outside', 'Garciamouth', 'maintain', 197, 'upon', 'nor',
(198, 'class', 'East Melissamouth', 'discover', 198, 'study', 'option',
(199, 'though', 'Whiteberg', 'relationship', 199, 'land', 'quickly',
(200, 'on', 'New Amberside', 'top', 200, 'business', 'skill',
(201, 'detail', 'Gloriabury', 'among', 201, 'great', 'seek',
(202, 'war', 'South Ericport', 'yes', 202, 'degree', 'worker',
(203, 'wish', 'Daisyport', 'parent', 203, 'mother', 'all',
(204, 'name', 'East Max', 'bring', 204, 'cold', 'present',
(205, 'simple', 'New Nancy', 'understand', 205, 'per', 'agent',
(206, 'week', 'North Elaine', 'firm', 206, 'hope', 'minute',
(207, 'near', 'South Davidton', 'focus', 207, 'house', 'area',
(208, 'bad', 'Williamside', 'cultural', 208, 'still', 'color',
(209, 'price', 'Port Shannonview', 'under', 209, 'institution', 'weight',
(210, 'responsibility', 'Butlerstad', 'television', 210, 'religious', 'financial',
(211, 'for', 'Victorstad', 'place', 211, 'training', 'voice',
(212, 'see', 'Aaronton', 'ok', 212, 'reach', 'live',
(213, 'positive', 'South Meganside', 'door', 213, 'boy', 'pressure',
(214, 'return', 'Hillside', 'true', 214, 'challenge', 'international',
(215, 'special', 'New Laurie', 'detail', 215, 'environmental', 'challenge',
(216, 'measure', 'Michaelville', 'image', 216, 'plan', 'significant',
(217, 'institution', 'South Jonathanstad', 'sure', 217, 'a', 'ahead',
(218, 'theory', 'South Ashleyburgh', 'go', 218, 'cover', 'can',
(219, 'form', 'Serranoport', 'room', 219, 'value', 'him',
(220, 'actually', 'Sarahville', 'white', 220, 'figure', 'save',
(221, 'people', 'Barbaraburgh', 'civil', 221, 'catch', 'face',
(222, 'strategy', 'New Jenniferfort', 'administration', 222, 'guy', 'person',
(223, 'meeting', 'Saraburgh', 'finally', 223, 'event', 'eight',
(224, 'letter', 'East Gailside', 'speak', 224, 'ever', 'team',
(225, 'day', 'Lake Tonyberg', 'first', 225, 'learn', 'drive',
(226, 'these', 'Port Ashleyfort', 'near', 226, 'who', 'safe',
(227, 'interesting', 'New Johnberg', 'black', 227, 'coach', 'share',
(228, 'would', 'Mitchellport', 'term', 228, 'game', 'board',
(229, 'for', 'Barronhaven', 'summer', 229, 'food', 'recognize',
(230, 'central', 'Yangberg', 'difficult', 230, 'charge', 'nice',
(231, 'need', 'Fisherland', 'final', 231, 'billion', 'must',
(232, 'anything', 'East Elizabeth', 'water', 232, 'learn', 'our',
(233, 'right', 'New Karenberg', 'forget', 233, 'make', 'plant',
(234, 'back', 'Armstrongberg', 'available', 234, 'truth', 'claim',
(235, 'add', 'Jessicahaven', 'alone', 235, 'society', 'couple',
(236, 'road', 'North Christopherton', 'analysis', 236, 'protect', 'consumer',
(237, 'single', 'North Kara', 'receive', 237, 'can', 'idea',
(238, 'range', 'South Anthonyfurt', 'human', 238, 'room', 'edge',
(239, 'machine', 'Butlerberg', 'significant', 239, 'drug', 'few',
(240, 'her', 'East Stevenfurt', 'painting', 240, 'call', 'method',
(241, 'strong', 'Lake Peter', 'successful', 241, 'blue', 'heavy',
(242, 'since', 'Teresaton', 'try', 242, 'score', 'campaign',
(243, 'party', 'South Mario', 'reflect', 243, 'small', 'blue',
(244, 'attack', 'Garciamouth', 'community', 244, 'physical', 'appear',
(245, 'network', 'Samuelmouth', 'race', 245, 'memory', 'when',
(246, 'rather', 'Michelleberg', 'administration', 246, 'world', 'sell',
(247, 'down', 'New Roberthaven', 'need', 247, 'rest', 'series',
(248, 'coach', 'Susanstad', 'management', 248, 'part', 'force',
(249, 'road', 'Robertfurt', 'accept', 249, 'whatever', 'accept',
(250, 'nor', 'West Michaelbury', 'money', 250, 'memory', 'charge',
(251, 'improve', 'Christopherland', 'suggest', 251, 'everyone', 'result',
(252, 'particularly', 'Lake Thomas', 'still', 252, 'none', 'then',
(253, 'spring', 'Port Brittanyview', 'station', 253, 'start', 'full',
(254, 'effect', 'North Robert', 'represent', 254, 'compare', 'conference',
(255, 'ok', 'South Edwardfurt', 'time', 255, 'act', 'operation',
(256, 'edge', 'North Albertton', 'though', 256, 'although', 'international',
(257, 'practice', 'Danielville', 'industry', 257, 'development', 'eight',
(258, 'politics', 'West Rogerfort', 'anyone', 258, 'college', 'fire',
(259, 'feel', 'Charlesport', 'guess', 259, 'break', 'mention',
(260, 'stay', 'Lake Cliffordberg', 'no', 260, 'where', 'language',
(261, 'leg', 'Lake Richardborough', 'authority', 261, 'indeed', 'south',
(262, 'know', 'Ibarraberg', 'open', 262, 'return', 'short',
(263, 'goal', 'South Markberg', 'term', 263, 'six', 'trouble',
(264, 'night', 'Patrickview', 'heart', 264, 'new', 'late',
(265, 'member', 'East Johnny', 'situation', 265, 'call', 'would',
(266, 'experience', 'Anthonyville', 'accept', 266, 'election', 'long',
(267, 'six', 'Port John', 'read', 267, 'participant', 'rock',
(268, 'doctor', 'New Christina', 'war', 268, 'major', 'stage',
(269, 'pass', 'Kylefort', 'wait', 269, 'agreement', 'industry',
(270, 'heart', 'Hamiltonland', 'think', 270, 'range', 'boy',
(271, 'control', 'Lake Lindsayport', 'worry', 271, 'fill', 'just',
(272, 'design', 'North Anthonyton', 'amount', 272, 'hour', 'car',
(273, 'themselves', 'Callahanbury', 'red', 273, 'PM', 'according',
(274, 'leave', 'Vincentborough', 'process', 274, 'church', 'event',
(275, 'home', 'Ryanshire', 'hit', 275, 'research', 'agent',
(276, 'might', 'Maryberg', 'interview', 276, 'drive', 'a',
(277, 'specific', 'New Brooke', 'serve', 277, 'imagine', 'reality',
(278, 'out', 'North Josephmouth', 'year', 278, 'while', 'read',
(279, 'score', 'Wilsonton', 'tree', 279, 'able', 'note',
(280, 'happy', 'Parkerfort', 'any', 280, 'financial', 'white',
(281, 'special', 'Pamelastad', 'start', 281, 'drive', 'whom',
(282, 'center', 'East Karenside', 'conference', 282, 'option', 'and',
(283, 'result', 'New Heather', 'game', 283, 'quality', 'crime',
(284, 'argue', 'Amyfort', 'represent', 284, 'guess', 'improve',
(285, 'likely', 'Lake Kennethtown', 'force', 285, 'high', 'would',
(286, 'medical', 'Martinezbury', 'officer', 286, 'vote', 'open',
(287, 'south', 'East Betty', 'past', 287, 'response', 'after',
(288, 'community', 'Jessicaburgh', 'indeed', 288, 'lawyer', 'agency',
(289, 'policy', 'Lake Gregoryfurt', 'artist', 289, 'main', 'occur',
(290, 'office', 'Rogerland', 'style', 290, 'civil', 'school',
(291, 'determine', 'Jamiebury', 'economy', 291, 'finally', 'cold',
(292, 'vote', 'Petersonbury', 'pretty', 292, 'technology', 'expect',
(293, 'today', 'West Samuelborough', 'meet', 293, 'in', 'every',
(294, 'message', 'Matthewborough', 'his', 294, 'century', 'free',
(295, 'ground', 'Kimberg', 'against', 295, 'outside', 'group',
(296, 'blood', 'Port Adam', 'painting', 296, 'stand', 'resource',
(297, 'establish', 'Simsfort', 'game', 297, 'yet', 'group',
(298, 'even', 'Melissaview', 'outside', 298, 'kid', 'claim',
(299, 'me', 'Henryberg', 'base', 299, 'human', 'true',
(300, 'sing', 'Morganhaven', 'point', 300, 'hundred', 'thing');