INSERT INTO db_employee (department_id, first_name, id, last_name, salary)
VALUES (1, 'Sarah Greene MD', 1, 'Angela Clark', 'try',
(2, 'Christopher Roberts', 2, 'Collin Gallegos', 'pass',
(3, 'Andrew Gay', 3, 'Adam Wagner', 'account',
(4, 'Rachael Porter', 4, 'Cory Ross', 'yet',
(5, 'Joshua Nixon DDS', 5, 'Tiffany James', 'school',
(6, 'Matthew Walker', 6, 'Abigail Cervantes', 'relationship',
(7, 'Douglas Hill', 7, 'Brittany Buckley', 'significant',
(8, 'Cheryl Petersen', 8, 'Mike Hawkins', 'shake',
(9, 'Megan Irwin', 9, 'Erik Reid', 'account',
(10, 'Elizabeth Hudson', 10, 'Tricia Macias', 'agent',
(11, 'Amy David', 11, 'Kathryn Patterson', 'successful',
(12, 'David Ho', 12, 'Matthew Dominguez', 'total',
(13, 'Daniel Henson', 13, 'Sarah Fowler', 'difference',
(14, 'Morgan Nunez', 14, 'Maria Burke', 'event',
(15, 'Kristina Black', 15, 'Kristen Snow', 'produce',
(16, 'Alexander Pope', 16, 'Jackie Dixon', 'fly',
(17, 'Michael Duncan', 17, 'Michael Bennett', 'including',
(18, 'Thomas Davis', 18, 'Ana Gray', 'reflect',
(19, 'Kelly Thomas', 19, 'Patrick Johnson', 'animal',
(20, 'Melissa Valdez', 20, 'Angela Carter', 'fish',
(21, 'Krista Erickson', 21, 'Thomas Liu', 'true',
(22, 'Lisa Black', 22, 'Mary Gonzalez', 'bring',
(23, 'Amanda Golden', 23, 'Jay Gutierrez', 'yourself',
(24, 'Sheri Sanchez', 24, 'Joshua Evans', 'and',
(25, 'David Brown', 25, 'Edward Taylor', 'will',
(26, 'Amy Davis', 26, 'Michael Henry', 'mother',
(27, 'Amy Crawford', 27, 'Daniel Benton', 'candidate',
(28, 'William Frye', 28, 'Aaron Carter', 'too',
(29, 'Donna Scott', 29, 'Anthony Butler', 'financial',
(30, 'Ashley Arnold', 30, 'Ryan Cole', 'she',
(31, 'Samantha Watson', 31, 'Timothy Patel', 'international',
(32, 'Melanie Gibson', 32, 'Phillip Martin', 'eight',
(33, 'Crystal Diaz', 33, 'John Henderson', 'against',
(34, 'Mr. Jeffrey Miller', 34, 'David Palmer', 'billion',
(35, 'Michael Jackson', 35, 'Jasmine Jackson', 'wide',
(36, 'Krystal Ortiz', 36, 'Spencer Jones', 'north',
(37, 'Regina Parks', 37, 'Jamie Park', 'total',
(38, 'Ellen Graves', 38, 'Katherine Turner', 'for',
(39, 'Amanda Gilbert', 39, 'Cindy Johnson', 'challenge',
(40, 'Paul Avery', 40, 'Michael Walker', 'piece',
(41, 'Andrew Collins', 41, 'Matthew Gutierrez', 'pull',
(42, 'Lance Bolton', 42, 'Harry Zhang', 'view',
(43, 'Teresa Norman', 43, 'Amber Everett', 'law',
(44, 'Hayley Smith', 44, 'Kyle Oliver', 'imagine',
(45, 'Maria Elliott', 45, 'Teresa Burton', 'day',
(46, 'Anthony Wright', 46, 'Adam Scott', 'radio',
(47, 'David Santiago', 47, 'Cristina Keller', 'than',
(48, 'Danielle Lee', 48, 'Barbara Neal', 'throw',
(49, 'Frank Thornton', 49, 'Kendra Turner', 'report',
(50, 'David Kennedy', 50, 'Sarah Alvarez', 'board',
(51, 'Brooke Padilla', 51, 'Mrs. Samantha Barker', 'on',
(52, 'Tina Chavez', 52, 'Chad Hill', 'and',
(53, 'Julia Rangel', 53, 'Jessica Parker', 'nothing',
(54, 'Christopher Anderson', 54, 'Terry Day', 'different',
(55, 'John Daniels', 55, 'James Webb', 'reality',
(56, 'Patrick Johnson MD', 56, 'Stacy Hernandez', 'as',
(57, 'Antonio Hobbs', 57, 'Stanley Jackson', 'even',
(58, 'Justin Cline', 58, 'Katie Houston', 'employee',
(59, 'Kenneth Ward', 59, 'Roger Ortiz', 'world',
(60, 'Brian Fields', 60, 'Scott Peters', 'person',
(61, 'Lisa Rogers', 61, 'Kathy Nelson', 'down',
(62, 'Annette Wood', 62, 'Frank Collins', 'research',
(63, 'Allen Graham', 63, 'Stephen Perez', 'couple',
(64, 'Katrina Newman', 64, 'James Mcgee', 'yeah',
(65, 'Brendan Johnson', 65, 'Julie Sanchez', 'buy',
(66, 'Maria Rivera', 66, 'Zachary Kramer', 'night',
(67, 'Jennifer Morgan', 67, 'Jonathan Gonzalez MD', 'son',
(68, 'Adam Lopez', 68, 'Logan Chandler', 'laugh',
(69, 'Patrick Pittman', 69, 'Justin Robbins', 'feel',
(70, 'Jane Parker', 70, 'William Terry', 'option',
(71, 'Dr. David Miller', 71, 'William Lewis', 'itself',
(72, 'Elizabeth Rivas', 72, 'Julie Ritter', 'likely',
(73, 'Shawna Delgado', 73, 'Leslie Lopez', 'sign',
(74, 'Fred Wright', 74, 'Michael Baker', 'report',
(75, 'Michelle Underwood', 75, 'Amanda Larson', 'sea',
(76, 'Bethany Clements', 76, 'Edwin Johnson', 'lot',
(77, 'Cathy Pham', 77, 'Amy Robinson', 'property',
(78, 'Brent Miller', 78, 'Jason Gonzalez', 'under',
(79, 'Jimmy Park', 79, 'Katrina Stewart', 'fill',
(80, 'Lisa Oconnor', 80, 'Christopher Curtis', 'reason',
(81, 'Jamie Barker', 81, 'Thomas Obrien', 'cause',
(82, 'Bryan Herrera', 82, 'Mr. Anthony Lopez', 'public',
(83, 'Nicole Rose', 83, 'Lawrence Webb', 'baby',
(84, 'William Lawrence', 84, 'Brenda Mccoy', 'exist',
(85, 'Ms. Jennifer Perez', 85, 'Jim Alvarado', 'base',
(86, 'Annette Johnson', 86, 'Joseph Rubio', 'her',
(87, 'Jonathan Donovan', 87, 'Cassandra Davidson', 'strategy',
(88, 'Jamie Cole', 88, 'Benjamin Rhodes', 'paper',
(89, 'Louis Baker', 89, 'Joshua Wheeler', 'company',
(90, 'Kevin Graham', 90, 'Elizabeth Lynch', 'Congress',
(91, 'Joshua Miller', 91, 'Jeffery Dudley', 'ever',
(92, 'Nathaniel Dalton', 92, 'Tony Rogers', 'chair',
(93, 'Kathryn Garcia', 93, 'Cristina Conley', 'operation',
(94, 'Mr. James Rodriguez', 94, 'Darin Montgomery II', 'dinner',
(95, 'Lisa Hayes MD', 95, 'Eric Johnston', 'college',
(96, 'Amy Smith', 96, 'Michael Johnson', 'true',
(97, 'Raymond Rodriguez', 97, 'Matthew Thomas', 'all',
(98, 'Michael Espinoza', 98, 'Marie Mitchell', 'nature',
(99, 'Kenneth Brown', 99, 'Mrs. Dawn Gamble DDS', 'story',
(100, 'Christy Griffin', 100, 'Steven Hooper', 'reason',
(101, 'Andrea Crawford', 101, 'Gary Huff', 'fast',
(102, 'Jennifer Ayers MD', 102, 'Amy Koch', 'character',
(103, 'Tammy Graham', 103, 'Danielle Smith', 'rest',
(104, 'Sharon Mcknight', 104, 'Jennifer Sharp', 'easy',
(105, 'Zachary Sullivan', 105, 'Alexander Powers', 'cup',
(106, 'Stephanie Estrada', 106, 'Jacob Fox', 'senior',
(107, 'Roy Smith', 107, 'Elizabeth Gutierrez', 'customer',
(108, 'Adam Johnson', 108, 'Nancy Leonard', 'history',
(109, 'James Hodges', 109, 'Melissa Ward', 'use',
(110, 'Brandy Lee', 110, 'Bryce Hernandez', 'player',
(111, 'Troy Perez', 111, 'Julian Spencer', 'machine',
(112, 'Linda Coleman', 112, 'Timothy Davis', 'throw',
(113, 'Robin Frye', 113, 'Christina Gibson', 'bring',
(114, 'Johnathan Zimmerman', 114, 'Michael Smith', 'building',
(115, 'Ronald Williams', 115, 'Natasha Kidd', 'boy',
(116, 'Patricia Rivera', 116, 'Brittney Diaz', 'officer',
(117, 'Franklin Hernandez', 117, 'Daniel Dixon', 'campaign',
(118, 'Michael Villarreal', 118, 'Ryan Taylor', 'everybody',
(119, 'Ronald Reed', 119, 'Jenna Hill', 'model',
(120, 'Robert Simmons', 120, 'James Riggs', 'wait',
(121, 'Roger Lloyd', 121, 'Kristin Chase PhD', 'myself',
(122, 'Dr. Erin Marsh DVM', 122, 'Tammy Kerr', 'none',
(123, 'Erin Turner', 123, 'Allison Huffman', 'carry',
(124, 'Linda Jones', 124, 'Diane Watson', 'protect',
(125, 'Jasmine Lester', 125, 'Brandon King', 'land',
(126, 'Christine Ferrell', 126, 'Brandon Armstrong', 'air',
(127, 'Brian Goodman', 127, 'Roger Shaw', 'yard',
(128, 'Tina Fields', 128, 'Ryan Stuart', 'whether',
(129, 'Charles Mayer', 129, 'Bradley Doyle', 'consumer',
(130, 'Amanda Giles', 130, 'Benjamin Arellano', 'make',
(131, 'Eric Russell', 131, 'Tammy Elliott', 'reduce',
(132, 'John Hunter', 132, 'Tracey Harris', 'bar',
(133, 'Diana Lee', 133, 'Kristi Rice', 'peace',
(134, 'Sydney Santiago', 134, 'Megan Davies', 'team',
(135, 'Scott Adkins', 135, 'Stephanie Calhoun', 'whether',
(136, 'Amy Anderson', 136, 'Heidi Brown', 'tell',
(137, 'Ian Anthony', 137, 'Johnny Fischer', 'his',
(138, 'Heather Mccoy', 138, 'Michael Henderson', 'painting',
(139, 'Lauren Brown', 139, 'Anne Cochran', 'part',
(140, 'Lisa Jones', 140, 'Alicia Thompson', 'ago',
(141, 'John Hansen', 141, 'Kelly Roth', 'quality',
(142, 'Heidi Schultz', 142, 'Tara Obrien', 'degree',
(143, 'Nicole Hopkins', 143, 'Katherine Kelly', 'feel',
(144, 'Geoffrey Burke', 144, 'Brian Vincent', 'rule',
(145, 'Emily Watson', 145, 'Kyle Manning', 'police',
(146, 'Dr. Marcus Moore', 146, 'Andrew Smith', 'look',
(147, 'Maria Castillo', 147, 'Julie Kramer', 'hot',
(148, 'Timothy Todd', 148, 'Robert Dominguez', 'research',
(149, 'Joseph Krueger', 149, 'Michelle Flores', 'method',
(150, 'Richard Paul', 150, 'Joshua Griffith', 'full',
(151, 'Tammie Tran', 151, 'Sarah Sanchez', 'arm',
(152, 'Nicole Bradshaw', 152, 'Jacob Mann', 'paper',
(153, 'Caleb Stewart', 153, 'Sheila Simpson', 'follow',
(154, 'Daniel Edwards', 154, 'Gary Williams', 'gun',
(155, 'Kimberly Patton', 155, 'Jodi King', 'authority',
(156, 'Diana Cruz', 156, 'Alexis Nguyen', 'arrive',
(157, 'Dan Smith', 157, 'Emily Pratt', 'short',
(158, 'Kristina Reyes', 158, 'Dr. Alexandra Landry MD', 'indicate',
(159, 'Andrea Johnson', 159, 'Alexander Costa', 'several',
(160, 'Karla Huber', 160, 'Joseph Tucker', 'clearly',
(161, 'James Bowman', 161, 'Martha Moreno MD', 'short',
(162, 'Rebecca Wilson', 162, 'James Johnson', 'suffer',
(163, 'Michael Nguyen', 163, 'Michael Bradford', 'morning',
(164, 'Dustin Moore', 164, 'Amy Rodriguez', 'condition',
(165, 'Dr. Joy Dawson', 165, 'Bryan Parker', 'threat',
(166, 'Susan Harrison', 166, 'Jose Myers', 'consider',
(167, 'Whitney Black', 167, 'Dr. Ashley Barajas', 'themselves',
(168, 'Alexis Cohen', 168, 'Danielle Jones', 'major',
(169, 'Christopher Harris', 169, 'Brian Campbell', 'stage',
(170, 'Bryan Murray', 170, 'Mike Underwood', 'choice',
(171, 'Leslie Clark', 171, 'Raven Brown', 'suffer',
(172, 'Abigail Roberts', 172, 'Daniel Brown', 'federal',
(173, 'Sara Frost', 173, 'Chris Sloan', 'body',
(174, 'Cody Golden', 174, 'Joshua Mcneil', 'discover',
(175, 'Joseph Davies', 175, 'Denise Guerrero', 'on',
(176, 'Alexandra Guzman', 176, 'Donna Chang', 'receive',
(177, 'David Carpenter', 177, 'Hannah Combs', 'Democrat',
(178, 'Aaron Clark', 178, 'Jaime Stephenson', 'memory',
(179, 'Brianna Jimenez', 179, 'Joseph Williams', 'what',
(180, 'Michael Eaton', 180, 'Alfred Richardson', 'bank',
(181, 'Terry Perez', 181, 'Jennifer Cole', 'left',
(182, 'Nichole Welch', 182, 'James Hancock', 'history',
(183, 'Nicholas Davis', 183, 'Joseph Marshall', 'student',
(184, 'Lisa Moss', 184, 'Olivia Avery', 'debate',
(185, 'Jessica Hughes', 185, 'James Wheeler', 'current',
(186, 'Vincent Clay', 186, 'Jonathan Gray', 'ask',
(187, 'Hunter Rodriguez', 187, 'Bradley Jones', 'cover',
(188, 'Shelley Thomas', 188, 'James Lee', 'entire',
(189, 'Lisa Sanchez', 189, 'Martin Williams', 'figure',
(190, 'Angela Sanchez', 190, 'Patrick Day', 'account',
(191, 'Jonathan Thomas', 191, 'Jennifer Johnson', 'civil',
(192, 'Deanna Flores', 192, 'Greg Brown', 'measure',
(193, 'Michael Robinson', 193, 'Anthony Pruitt', 'hit',
(194, 'Ms. Megan Miller DDS', 194, 'Cody Shaw', 'yourself',
(195, 'Michael Flores', 195, 'Dr. Kevin Williams', 'body',
(196, 'Traci Torres', 196, 'Joy Hobbs', 'foreign',
(197, 'Michael Evans', 197, 'Jonathan Vasquez', 'decade',
(198, 'Daniel Martinez MD', 198, 'David Ellison', 'pull',
(199, 'Christopher Young', 199, 'Doris Williams', 'quite',
(200, 'Dylan Obrien', 200, 'Deborah Sandoval', 'since',
(201, 'Sandra Mills', 201, 'Jennifer Roberts', 'fine',
(202, 'Vanessa Hall', 202, 'Derek King', 'book',
(203, 'Lisa Wilkins', 203, 'Brooke Ramos', 'window',
(204, 'David Murphy', 204, 'Crystal Whitaker', 'speech',
(205, 'Jacob Green', 205, 'Douglas Macias', 'service',
(206, 'Dennis Williamson', 206, 'Stephen Prince', 'which',
(207, 'Rebecca Collins', 207, 'Christina Jackson', 'foreign',
(208, 'Anthony Rasmussen', 208, 'Ashley Elliott', 'democratic',
(209, 'Stephanie Mcdowell', 209, 'John Riley', 'place',
(210, 'Matthew West', 210, 'Karen Fuller', 'attack',
(211, 'Christina Braun', 211, 'Alexandria Edwards', 'place',
(212, 'George Ruiz', 212, 'Daniel Riley', 'career',
(213, 'James Ramirez', 213, 'Robert Davis', 'majority',
(214, 'Thomas Sanders', 214, 'Patricia Stafford', 'campaign',
(215, 'Sherri Gomez', 215, 'Vincent Cox', 'history',
(216, 'Andrea Anderson', 216, 'Benjamin Brown', 'dream',
(217, 'Brandon Blake', 217, 'Andrew Baker', 'start',
(218, 'Savannah Johnson', 218, 'Leonard Torres', 'site',
(219, 'Kayla Lee', 219, 'Melissa Glass', 'not',
(220, 'Jennifer Tucker', 220, 'Tara Kirby', 'year',
(221, 'Curtis Lane', 221, 'Joel Schmidt', 'help',
(222, 'Alex Griffin', 222, 'Joshua Glover', 'central',
(223, 'Wayne Anderson', 223, 'Jason Gonzales', 'system',
(224, 'Zachary Wolfe', 224, 'Shawn Stewart', 'finally',
(225, 'Carol Martinez', 225, 'James Gutierrez', 'positive',
(226, 'Natasha Lee', 226, 'Karen Shannon', 'wait',
(227, 'Amy Figueroa', 227, 'Aaron Day', 'sport',
(228, 'Jonathan Murphy', 228, 'Gregory Williams', 'which',
(229, 'Hannah Jackson', 229, 'Michael Melton', 'through',
(230, 'Christopher Knight', 230, 'Robert White', 'compare',
(231, 'Dr. Michael Chang', 231, 'Victor Jackson', 'arrive',
(232, 'Zachary Coleman', 232, 'Jennifer Johnson DDS', 'nothing',
(233, 'Pamela Duran', 233, 'Barbara Clark', 'ever',
(234, 'Terry Martin', 234, 'Michelle Young', 'expert',
(235, 'Emily Fitzgerald DDS', 235, 'Stephanie Ochoa', 'thank',
(236, 'Maurice Petersen', 236, 'Juan Little', 'occur',
(237, 'Michael Taylor', 237, 'Gregory Gutierrez', 'great',
(238, 'Lisa Rodgers MD', 238, 'Julia Craig', 'before',
(239, 'Alex Brown', 239, 'Kenneth Tran', 'organization',
(240, 'James Salazar', 240, 'Cynthia Hernandez', 'improve',
(241, 'Erica Hicks', 241, 'Tami Vance', 'difficult',
(242, 'Ashley Harrison', 242, 'Patrick Johnson', 'government',
(243, 'Ronald Bailey', 243, 'Brian Manning', 'start',
(244, 'Christopher Smith', 244, 'Jacob Rosales', 'mean',
(245, 'Jordan Brennan', 245, 'Edward Carroll', 'interest',
(246, 'Cheryl Mejia', 246, 'Hannah Reynolds', 'us',
(247, 'Aaron Watson', 247, 'Danielle Christensen', 'media',
(248, 'Scott Bennett', 248, 'Jeffrey Lewis', 'mouth',
(249, 'Tammy Stewart', 249, 'Sharon Walters', 'region',
(250, 'Kevin Herring', 250, 'Marie Hamilton', 'response',
(251, 'Michael Dixon', 251, 'David Smith', 'song',
(252, 'Thomas Ford', 252, 'Donna Guerra', 'well',
(253, 'Melissa Norton', 253, 'Kathleen Huffman', 'certain',
(254, 'Marc King', 254, 'Elizabeth Zimmerman', 'organization',
(255, 'Ann Lewis', 255, 'Destiny Garcia', 'food',
(256, 'Mitchell Brown MD', 256, 'David Allen', 'whatever',
(257, 'Jimmy Gill', 257, 'Joseph Jordan', 'run',
(258, 'William Brown', 258, 'Mary Lloyd', 'smile',
(259, 'Cindy Rogers', 259, 'Christina Johnston', 'future',
(260, 'Wanda Wilson', 260, 'Jeffery Barry', 'benefit',
(261, 'Teresa Ortiz', 261, 'Ashley Macdonald', 'main',
(262, 'Logan Hill', 262, 'Ryan Harper', 'government',
(263, 'William Jones', 263, 'Jennifer Bryant', 'individual',
(264, 'Yolanda Patterson', 264, 'James Carey', 'you',
(265, 'Antonio Porter', 265, 'Patricia Parker', 'teacher',
(266, 'Warren White', 266, 'Shelly Reynolds', 'edge',
(267, 'Joseph Brown', 267, 'Candace Herring', 'stop',
(268, 'Mary Bautista', 268, 'John Mora', 'fear',
(269, 'Jason Stark', 269, 'Shannon Smith', 'age',
(270, 'Teresa Morales', 270, 'Brittany Wagner', 'hundred',
(271, 'Deborah Cunningham', 271, 'Paula Daniels', 'husband',
(272, 'Michael Spencer', 272, 'Pamela Rogers', 'daughter',
(273, 'Kenneth Martin', 273, 'Jason Wright', 'purpose',
(274, 'Sharon Boyle', 274, 'Michael Turner', 'father',
(275, 'Aaron Garcia', 275, 'William Griffin', 'who',
(276, 'William Morgan', 276, 'Michael Bird', 'prevent',
(277, 'Matthew Velazquez', 277, 'Kathryn Taylor', 'agent',
(278, 'Michael Watson', 278, 'Brittany Becker', 'one',
(279, 'Chris Lee', 279, 'Christopher Ross', 'expect',
(280, 'Ariel Morris', 280, 'Kimberly Campos', 'room',
(281, 'Joseph Hood', 281, 'Rachael Harris', 'marriage',
(282, 'Katherine Carrillo', 282, 'James Whitaker', 'exactly',
(283, 'Allison Mendez', 283, 'Tiffany Smith', 'line',
(284, 'Vanessa Mcdonald', 284, 'Mary Harris', 'able',
(285, 'Erika Cox', 285, 'Jennifer Hutchinson', 'red',
(286, 'Mr. Ralph Chapman', 286, 'Melissa Ashley', 'opportunity',
(287, 'Kevin Harrington', 287, 'Karina Miller', 'thus',
(288, 'Gregory Floyd', 288, 'Charles Fletcher', 'career',
(289, 'Adriana Duncan', 289, 'William Smith', 'democratic',
(290, 'Dr. Alan Cardenas', 290, 'David Underwood', 'attention',
(291, 'Jennifer Davis', 291, 'Ashley Nelson', 'our',
(292, 'Andre Monroe', 292, 'Erin Ortiz', 'under',
(293, 'Edward Stevens', 293, 'Jordan Smith', 'kid',
(294, 'Kimberly Steele MD', 294, 'Jacqueline Gutierrez', 'sort',
(295, 'Nathaniel Curry', 295, 'Kyle Sanders', 'industry',
(296, 'Cheryl Herman', 296, 'Crystal Brown', 'provide',
(297, 'Kathryn Hancock', 297, 'Kayla Sherman', 'also',
(298, 'Jason Abbott', 298, 'Brianna Wilson', 'tonight',
(299, 'Michelle Roy', 299, 'Barbara Horne', 'result',
(300, 'Michael Hernandez', 300, 'David Turner', 'design');