INSERT INTO dim_customer (cust_city, cust_dob, cust_id, cust_name, cust_pin_code)
VALUES ('Lanemouth', 'think', 1, 'Adrian Hansen', 'drive',
('Lake Annaview', 'enter', 2, 'Whitney Taylor', 'score',
('Noahton', 'future', 3, 'Dawn Henderson', 'some',
('North Vincentmouth', 'smile', 4, 'Michael Perkins', 'size',
('East Michelle', 'by', 5, 'Daniel Lee', 'medical',
('South Kurtton', 'song', 6, 'James Sandoval', 'throughout',
('Port Ericmouth', 'power', 7, 'Terry Ruiz', 'garden',
('Bradleybury', 'none', 8, 'Dr. Jamie Wilkins', 'too',
('Frederickchester', 'consumer', 9, 'Kelly Ortiz', 'reduce',
('Lake Justinview', 'work', 10, 'Joshua Gilmore', 'mean',
('West Stanleychester', 'arm', 11, 'Regina Boyd', 'age',
('South Paul', 'imagine', 12, 'Stephanie Jones', 'employee',
('West Nicole', 'ground', 13, 'Maria Rodriguez', 'off',
('Lake Jeffrey', 'hit', 14, 'Matthew Hubbard', 'back',
('Wilsonfort', 'leg', 15, 'Kevin Gonzales', 'decision',
('Smithmouth', 'best', 16, 'Brenda Sanchez', 'bag',
('Port Stevenfort', 'wrong', 17, 'John Ford', 'identify',
('New Billbury', 'series', 18, 'Christine Martin', 'citizen',
('New Paulmouth', 'how', 19, 'Andres Frazier', 'see',
('New Jennifer', 'various', 20, 'Lori Smith', 'decision',
('Shanestad', 'officer', 21, 'Ruth Leach', 'ok',
('West Sean', 'officer', 22, 'Stephanie Castro', 'perhaps',
('Sydneymouth', 'toward', 23, 'Audrey Dickerson', 'blue',
('Robertmouth', 'condition', 24, 'Jennifer Nguyen', 'clearly',
('South Chelseaborough', 'central', 25, 'Randall Rojas', 'PM',
('Carsonport', 'bed', 26, 'Christopher Oconnor', 'the',
('West Jason', 'attorney', 27, 'Joseph Wilson', 'energy',
('West Jessica', 'difficult', 28, 'Maria Sandoval', 'add',
('Brookshaven', 'ground', 29, 'Nathan Thompson', 'from',
('Lake Lisa', 'road', 30, 'Nathan Klein', 'off',
('Danielleside', 'share', 31, 'Jonathan Mason', 'participant',
('Lake Crystal', 'see', 32, 'Lonnie Thomas', 'claim',
('Port Randy', 'just', 33, 'Laura Griffin', 'see',
('Port Mikeview', 'debate', 34, 'Lori Vaughn', 'group',
('Solomonborough', 'should', 35, 'James Schmidt', 'ball',
('South Donnaside', 'from', 36, 'Thomas Hubbard', 'current',
('South Jennifer', 'site', 37, 'Robert Alvarez', 'couple',
('Ericberg', 'together', 38, 'Tracy Hill', 'white',
('North Adam', 'answer', 39, 'Maria Wright', 'child',
('Markside', 'sell', 40, 'Sara Dixon', 'huge',
('Scottburgh', 'his', 41, 'Erin Freeman', 'power',
('Collinsport', 'job', 42, 'Brittney White', 'usually',
('South Malik', 'skin', 43, 'Michael Nash', 'choice',
('North Charlesmouth', 'course', 44, 'Misty Garcia', 'by',
('New Angela', 'data', 45, 'Laura Benjamin', 'forget',
('Sampsonshire', 'wait', 46, 'Amanda Griffin', 'baby',
('New Yvonne', 'keep', 47, 'Michael Smith', 'in',
('Kevinhaven', 'resource', 48, 'Nichole Mclean', 'despite',
('Timothymouth', 'west', 49, 'Alexis Garcia', 'idea',
('South Joseph', 'deep', 50, 'Michelle Rodriguez', 'coach',
('Lake Mauriceland', 'write', 51, 'Gary Richardson', 'much',
('Lake Colleenburgh', 'major', 52, 'Eric Park', 'gun',
('Port Courtney', 'collection', 53, 'Robert Cole', 'radio',
('Petersonborough', 'including', 54, 'Dr. Casey Morris', 'together',
('Port Josephmouth', 'early', 55, 'Craig Murray', 'term',
('Yvetteville', 'write', 56, 'Maria Alexander', 'after',
('East Amyshire', 'these', 57, 'Tyler Martinez', 'might',
('North Kaylaville', 'manager', 58, 'Barry Thompson', 'four',
('North Kurt', 'within', 59, 'Ronald Garcia', 'peace',
('North Josephhaven', 'parent', 60, 'Kerry Smith', 'everybody',
('Lake Heatherburgh', 'news', 61, 'Paul Baker', 'game',
('South Dennisside', 'product', 62, 'Stacey Olson', 'couple',
('Pennystad', 'training', 63, 'Kelli Mullins', 'world',
('Mariahmouth', 'already', 64, 'Stephanie Reed', 'face',
('West Lisa', 'treat', 65, 'Stephanie Simmons', 'down',
('East Kristen', 'second', 66, 'Michele Lam', 'day',
('Amandaville', 'either', 67, 'Jeffrey Garcia', 'perform',
('Lake Margaret', 'no', 68, 'Andrea Higgins', 'trial',
('Bonillamouth', 'put', 69, 'Bryan Liu', 'agree',
('Nicholasfurt', 'guess', 70, 'Samantha Smith', 'source',
('West Leahfurt', 'give', 71, 'Lawrence Powell', 'challenge',
('Payneton', 'give', 72, 'Jessica Gibbs', 'movie',
('South Eric', 'wind', 73, 'Scott Guzman', 'again',
('Lawrencestad', 'trade', 74, 'Katelyn Lee', 'he',
('Gregoryberg', 'base', 75, 'Susan Kennedy', 'challenge',
('Webbshire', 'he', 76, 'Ronald Gordon', 'Mr',
('South Emily', 'listen', 77, 'Daniel Smith', 'article',
('East Jasonmouth', 'medical', 78, 'Michael Fernandez', 'once',
('Port Beckyburgh', 'citizen', 79, 'Laurie King', 'organization',
('Richardsside', 'environmental', 80, 'Melissa Luna', 'strong',
('Robertoville', 'toward', 81, 'Derek Diaz', 'nearly',
('New Jacqueline', 'least', 82, 'Brooke Long', 'south',
('New Jamesfort', 'truth', 83, 'Joshua Murray', 'space',
('North Bradleymouth', 'federal', 84, 'Linda Hicks', 'professor',
('New Gregory', 'none', 85, 'Gwendolyn Gardner', 'collection',
('South Carl', 'mission', 86, 'Brandon Preston', 'police',
('Hernandezberg', 'set', 87, 'Gerald Mack', 'feel',
('Julietown', 'through', 88, 'William Farrell', 'building',
('West Emily', 'instead', 89, 'Ryan Rivera', 'fund',
('North Luishaven', 'campaign', 90, 'Calvin Pineda', 'kid',
('New Josephmouth', 'create', 91, 'Robert Thomas', 'sister',
('Ewingburgh', 'woman', 92, 'Eric Crosby', 'black',
('West Ashley', 'final', 93, 'Priscilla Benjamin', 'we',
('Shaneville', 'feeling', 94, 'Deanna Hodge', 'why',
('Lake Zacharyville', 'book', 95, 'John Gill', 'tough',
('Smithport', 'bill', 96, 'Terry Vasquez', 'group',
('Timothyshire', 'level', 97, 'James Hall', 'explain',
('Joneshaven', 'energy', 98, 'Jacob Washington', 'factor',
('Feliciashire', 'soldier', 99, 'Jonathan Fields', 'avoid',
('Lake Tina', 'voice', 100, 'Michelle Cisneros', 'choose',
('East Aprilton', 'create', 101, 'Aaron Cooper', 'cold',
('Rogersside', 'eat', 102, 'Thomas Perez', 'line',
('Dawnberg', 'as', 103, 'Nathaniel Cook', 'including',
('North Linda', 'write', 104, 'Jessica Guerrero', 'serve',
('Lake Lisa', 'care', 105, 'Michael Sims', 'hour',
('South Jennifer', 'case', 106, 'Kenneth Hill', 'central',
('Mendezville', 'debate', 107, 'Cynthia Andrews', 'unit',
('Garciamouth', 'ahead', 108, 'Jason Barnes', 'production',
('East Jesus', 'suddenly', 109, 'Luke Edwards', 'minute',
('Hortonburgh', 'phone', 110, 'Elizabeth Collins', 'house',
('New Hannahmouth', 'have', 111, 'Michelle Schultz', 'opportunity',
('Lake Craigstad', 'small', 112, 'Jesse Miller', 'often',
('Greenton', 'travel', 113, 'Jeffrey Hayes', 'possible',
('West Marissaland', 'floor', 114, 'Richard Torres', 'might',
('Wangfurt', 'foot', 115, 'Martin Holder', 'represent',
('West Christopherstad', 'west', 116, 'Brad Brown', 'success',
('Jasontown', 'blood', 117, 'Nicole Richardson', 'whole',
('East Ian', 'system', 118, 'Natalie Rangel', 'present',
('Danielleburgh', 'up', 119, 'Kari Lopez', 'evidence',
('Millerport', 'walk', 120, 'Melissa Stevens', 'attention',
('East Ryanhaven', 'church', 121, 'Margaret Mcbride', 'significant',
('Alexanderport', 'guess', 122, 'Teresa Clayton', 'cultural',
('Elizabethshire', 'probably', 123, 'Justin Serrano', 'civil',
('New Andrewmouth', 'with', 124, 'Denise Ferguson', 'however',
('New Michaelchester', 'despite', 125, 'Robert Ferguson', 'similar',
('Carmenmouth', 'early', 126, 'Bryan Roy', 'art',
('New Robertmouth', 'natural', 127, 'James Fowler', 'sister',
('East Bryan', 'within', 128, 'Derek Greene', 'box',
('South Joshuaton', 'her', 129, 'Veronica Hardin DDS', 'fire',
('Taylorport', 'time', 130, 'Gerald Williams', 'discussion',
('East Lisamouth', 'past', 131, 'Daniel Ferguson', 'site',
('Stevenfort', 'bank', 132, 'Courtney Hopkins', 'chair',
('Cherylmouth', 'world', 133, 'Ronald Reed', 'lead',
('North Christopherborough', 'minute', 134, 'Emily Schneider', 'culture',
('North Steven', 'find', 135, 'Carrie Bishop', 'Mrs',
('North Thomaschester', 'father', 136, 'Michael Rodriguez', 'particular',
('Gonzalezstad', 'special', 137, 'Nicholas Johnston', 'inside',
('Port Paige', 'including', 138, 'Randall Burch', 'personal',
('North Tammy', 'effect', 139, 'Jessica Ford', 'its',
('Jenniferberg', 'respond', 140, 'Sarah Carey', 'dark',
('Port Laurenhaven', 'than', 141, 'Kimberly Ayala', 'room',
('Parkermouth', 'your', 142, 'Angela Choi', 'toward',
('West Seanborough', 'true', 143, 'Aaron Mcdonald', 'animal',
('Montoyahaven', 'they', 144, 'Brett Leach', 'question',
('North Gregory', 'return', 145, 'Stephanie Collins', 'space',
('Martinfurt', 'method', 146, 'Lisa Brooks', 'really',
('New Wendy', 'glass', 147, 'Jose Lopez', 'campaign',
('Woodsmouth', 'note', 148, 'Susan Griffin', 'fear',
('Francestown', 'morning', 149, 'Alexis Grant', 'decade',
('South Deborah', 'represent', 150, 'Carla Decker', 'through',
('West Thomas', 'cultural', 151, 'James Graham', 'goal',
('Lake Brandiberg', 'argue', 152, 'Eileen Murphy', 'water',
('Dalemouth', 'attorney', 153, 'Tracy Abbott', 'so',
('Port Richardville', 'receive', 154, 'Lori Webb', 'wrong',
('North Andre', 'crime', 155, 'Nicholas Tucker', 'message',
('Port Laurieshire', 'daughter', 156, 'Faith Martinez', 'whom',
('Joneschester', 'beat', 157, 'Kelly Lewis', 'item',
('East Sherylstad', 'story', 158, 'Douglas Ballard', 'find',
('Amymouth', 'computer', 159, 'Alexander Moss', 'method',
('Powersfurt', 'crime', 160, 'Jeffrey Montoya', 'land',
('Lake Justintown', 'of', 161, 'Nathaniel Patterson', 'later',
('Chandlerbury', 'remain', 162, 'Peter Robinson', 'up',
('North Traceychester', 'administration', 163, 'Justin Henderson', 'issue',
('South Shanestad', 'education', 164, 'Maria Pearson', 'everything',
('South Andrea', 'right', 165, 'Danielle Morris', 'oil',
('New Ronaldmouth', 'trip', 166, 'Tanya Mills', 'American',
('Tiffanyfort', 'employee', 167, 'Jenna Sloan', 'analysis',
('South Ann', 'star', 168, 'Brian Burns', 'role',
('North Brandonmouth', 'we', 169, 'Michael Irwin', 'box',
('Cynthiaville', 'increase', 170, 'Matthew Douglas', 'let',
('Gomezshire', 'figure', 171, 'Amanda Briggs', 'fly',
('Juliafort', 'other', 172, 'Robert Oneal', 'friend',
('New Kevin', 'structure', 173, 'Danielle Brown', 'environment',
('Allisonshire', 'argue', 174, 'Cheryl Klein', 'my',
('Lake Austinberg', 'data', 175, 'Randy Taylor', 'finish',
('Victoriamouth', 'a', 176, 'Priscilla Wallace', 'article',
('South Amberstad', 'also', 177, 'Isaac Kline', 'call',
('North Danielburgh', 'sell', 178, 'Molly Patterson', 'despite',
('Waltonstad', 'outside', 179, 'David Booth', 'information',
('Meghanborough', 'wish', 180, 'Mallory Lyons', 'quality',
('Thompsonland', 'woman', 181, 'Sara Lane', 'some',
('Lake Christopher', 'compare', 182, 'James Freeman', 'specific',
('South Wendy', 'sound', 183, 'Anthony Hull', 'car',
('West Jeremyport', 'feeling', 184, 'Brooke Johnson', 'billion',
('New Chadstad', 'claim', 185, 'Jessica Johnson', 'bar',
('Dixonshire', 'only', 186, 'John White', 'individual',
('Penashire', 'cost', 187, 'Nicholas Jackson', 'meeting',
('Johnmouth', 'forward', 188, 'Willie Brown', 'hundred',
('Austinland', 'more', 189, 'Angelica Summers', 'other',
('Taylorton', 'remember', 190, 'Ms. Kelli Moody', 'agency',
('Ronaldberg', 'forget', 191, 'Bryan Garrison', 'article',
('South Chloe', 'protect', 192, 'James Vega', 'realize',
('Welchmouth', 'type', 193, 'Ryan Williams', 'point',
('South William', 'social', 194, 'Pamela Rodriguez', 'practice',
('Millerfurt', 'eye', 195, 'Mr. Matthew Wood MD', 'local',
('Colemantown', 'adult', 196, 'Peter Gibbs', 'view',
('South Amanda', 'indeed', 197, 'Douglas French', 'other',
('New Leslie', 'hand', 198, 'Connie Foster', 'yet',
('South Kathleenfort', 'agent', 199, 'Bryan Hamilton', 'good',
('Ethantown', 'right', 200, 'Allen Villanueva', 'second',
('West Williamport', 'feeling', 201, 'Cindy Cook', 'though',
('Morganview', 'education', 202, 'Jacob Wheeler', 'environment',
('Edwardsburgh', 'much', 203, 'Robin Shaw', 'word',
('Jessicashire', 'door', 204, 'Miss Katelyn Lewis', 'firm',
('Brendaview', 'impact', 205, 'Aaron Hart', 'appear',
('Mejiamouth', 'meet', 206, 'Deanna Schneider', 'Republican',
('South Mindy', 'move', 207, 'Richard Butler', 'this',
('Owenport', 'general', 208, 'Dr. Betty Watson', 'seek',
('North Samuelborough', 'me', 209, 'Brent Roth', 'model',
('Campbellshire', 'eight', 210, 'Angela Harris', 'just',
('Kathryntown', 'down', 211, 'Jason Smith', 'describe',
('South Richard', 'well', 212, 'Ryan Barrera', 'future',
('Salazarstad', 'politics', 213, 'David Ochoa', 'ahead',
('Mitchellhaven', 'much', 214, 'Tiffany Martinez', 'land',
('Georgeville', 'debate', 215, 'Jennifer Cooper', 'type',
('Jonathanshire', 'usually', 216, 'Brandon Butler', 'with',
('Patrickland', 'your', 217, 'Todd Harvey', 'wonder',
('Henryburgh', 'better', 218, 'Jeff Wood', 'above',
('Bassbury', 'main', 219, 'Shelley Meyer', 'and',
('North Vincent', 'attack', 220, 'Julie Ortiz', 'industry',
('Brandonberg', 'lay', 221, 'Paul Lopez', 'measure',
('Powellshire', 'result', 222, 'Shelly Durham', 'newspaper',
('North Paul', 'board', 223, 'Kelly Morales', 'open',
('Brownland', 'practice', 224, 'Crystal Wilson', 'blood',
('Whiteville', 'age', 225, 'David Bowman', 'follow',
('East Johnside', 'day', 226, 'Joshua Martinez', 'beat',
('Port James', 'sure', 227, 'Jessica Nelson', 'crime',
('South Carrie', 'ready', 228, 'Scott Love', 'never',
('Abigailchester', 'structure', 229, 'Kirk Franklin', 'team',
('North Carrie', 'forget', 230, 'Matthew Galloway', 'candidate',
('Petersonbury', 'kind', 231, 'Alexander Torres', 'type',
('Christopherhaven', 'trouble', 232, 'David Guerrero', 'energy',
('Lisashire', 'top', 233, 'Matthew Ramirez', 'ok',
('Port Laurenville', 'week', 234, 'Erin Brown', 'different',
('Victoriaport', 'others', 235, 'Anthony Holmes', 'trial',
('South Robert', 'actually', 236, 'Sue Garcia', 'with',
('Tristanland', 'girl', 237, 'Samantha Clark', 'talk',
('Kelseybury', 'on', 238, 'Lindsey Rodgers', 'until',
('Kevinberg', 'marriage', 239, 'Todd Mcneil', 'east',
('West Melissahaven', 'allow', 240, 'Donna Walsh', 'attention',
('Justinfurt', 'enter', 241, 'Laurie Harris', 'official',
('Briannastad', 'cup', 242, 'Monica Shaffer', 'national',
('Lake Susanview', 'kitchen', 243, 'Maria Paul', 'myself',
('East Samuel', 'writer', 244, 'Stephen Hall', 'gun',
('New Susanborough', 'huge', 245, 'Christopher Petty', 'measure',
('West Sally', 'very', 246, 'David Hurley', 'wife',
('Lake Mary', 'five', 247, 'James Scott', 'certainly',
('South Patriciamouth', 'try', 248, 'Janice Ortiz', 'father',
('Davidland', 'push', 249, 'Jason Contreras', 'under',
('Bakerstad', 'beat', 250, 'Anita Davis', 'talk',
('Lewischester', 'more', 251, 'Heidi Phillips', 'land',
('Thomasbury', 'recently', 252, 'Stephanie Braun', 'determine',
('Ruizbury', 'control', 253, 'Joshua Martinez', 'seem',
('Kevinhaven', 'whose', 254, 'Cynthia White', 'together',
('Ericmouth', 'push', 255, 'Kari Ward', 'bill',
('West Danabury', 'bank', 256, 'Dennis Arnold', 'certainly',
('South John', 'sure', 257, 'Paul Ortega', 'house',
('New Ann', 'wish', 258, 'Rebecca Andrews', 'fish',
('Snyderport', 'development', 259, 'Brandon Smith', 'others',
('Dustinstad', 'arrive', 260, 'Stephen Adams', 'represent',
('Cameronshire', 'play', 261, 'Alex Warren', 'notice',
('Adamsshire', 'why', 262, 'Beth Mccall', 'born',
('Teresamouth', 'majority', 263, 'Jennifer Harrison', 'hundred',
('South Georgeborough', 'agency', 264, 'Michele Pitts', 'week',
('Annburgh', 'about', 265, 'Terry Shelton', 'firm',
('Fryebury', 'peace', 266, 'Megan Price', 'bed',
('Port Latoya', 'almost', 267, 'Michael Davis', 'environment',
('South Andrea', 'hand', 268, 'Daniel Norris', 'unit',
('Villanuevamouth', 'hair', 269, 'Andrea Montoya', 'piece',
('Davidmouth', 'future', 270, 'Frank Dalton', 'indicate',
('Jamieville', 'we', 271, 'Thomas Rice', 'beautiful',
('New Taylorbury', 'understand', 272, 'Lauren Caldwell', 'someone',
('Margaretshire', 'chair', 273, 'Tanya Marshall', 'whose',
('Robertsshire', 'line', 274, 'Nathaniel Thompson', 'case',
('Lake Saramouth', 'car', 275, 'Rachel Davidson', 'discover',
('Lake Josephtown', 'authority', 276, 'Richard Alexander', 'table',
('Tuckerburgh', 'early', 277, 'Crystal Stewart', 'side',
('West Tammymouth', 'executive', 278, 'Gwendolyn Aguirre', 'nice',
('South Maryborough', 'sign', 279, 'Andrea Sanders DDS', 'admit',
('East Clinton', 'person', 280, 'Jennifer Frank', 'stay',
('Lake Courtneyside', 'war', 281, 'Christopher Johnston', 'popular',
('West William', 'here', 282, 'Lisa Collins', 'today',
('Gordonton', 'sense', 283, 'Taylor Webb', 'nice',
('Hatfieldstad', 'determine', 284, 'John Miller', 'site',
('Martinchester', 'free', 285, 'Daniel Jones', 'college',
('Philipport', 'because', 286, 'Mary Torres', 'white',
('Courtneymouth', 'wish', 287, 'Zachary Young', 'stand',
('Davisville', 'seem', 288, 'Patricia Hernandez MD', 'program',
('South Tanyachester', 'happy', 289, 'Connie White', 'because',
('Marshhaven', 'scene', 290, 'Krista Smith', 'oil',
('Stephaniehaven', 'chair', 291, 'Tara Clark', 'same',
('Jessicashire', 'spend', 292, 'Maria Jackson', 'how',
('Edwardsmouth', 'course', 293, 'Darren Thomas', 'grow',
('Taylorstad', 'though', 294, 'Jonathan Swanson', 'money',
('Port Stephanie', 'development', 295, 'Dr. Thomas Ryan', 'doctor',
('South Dana', 'three', 296, 'Jonathan York', 'very',
('West Keithland', 'evening', 297, 'Madison Johnson', 'price',
('Maureenville', 'probably', 298, 'Melanie Cook', 'get',
('Chapmanmouth', 'growth', 299, 'Carlos Owens', 'work',
('South Shannon', 'draw', 300, 'Linda Anderson', 'military');