INSERT INTO fraud_score (claim_cost, fraud_score, policy_num, state)
VALUES ('two', 'build', 'concern', 'Maine',
('artist', 'light', 'even', 'Louisiana',
('rich', 'media', 'pass', 'West Virginia',
('treatment', 'seven', 'accept', 'North Carolina',
('page', 'kind', 'improve', 'New Mexico',
('fear', 'media', 'issue', 'Pennsylvania',
('job', 'total', 'from', 'West Virginia',
('challenge', 'morning', 'may', 'Wisconsin',
('shoulder', 'bad', 'always', 'South Carolina',
('at', 'least', 'cut', 'Idaho',
('suggest', 'so', 'doctor', 'Massachusetts',
('argue', 'deal', 'bad', 'Tennessee',
('he', 'same', 'rule', 'Indiana',
('support', 'out', 'parent', 'Montana',
('bar', 'someone', 'talk', 'Colorado',
('where', 'standard', 'happen', 'Maine',
('fine', 'tonight', 'me', 'Arkansas',
('ten', 'point', 'according', 'Delaware',
('model', 'from', 'wonder', 'Michigan',
('after', 'view', 'happy', 'Wyoming',
('parent', 'including', 'north', 'Montana',
('enter', 'day', 'itself', 'Michigan',
('degree', 'allow', 'process', 'Connecticut',
('else', 'join', 'improve', 'Missouri',
('alone', 'event', 'place', 'Mississippi',
('site', 'of', 'he', 'Michigan',
('near', 'should', 'generation', 'Maryland',
('forget', 'television', 'company', 'Alaska',
('investment', 'low', 'side', 'Arizona',
('ten', 'another', 'almost', 'North Dakota',
('my', 'this', 'memory', 'Georgia',
('after', 'prevent', 'anyone', 'Georgia',
('year', 'military', 'indicate', 'New Jersey',
('oil', 'camera', 'best', 'Illinois',
('product', 'eat', 'leave', 'Tennessee',
('stuff', 'but', 'conference', 'Oregon',
('institution', 'get', 'recently', 'Colorado',
('adult', 'force', 'after', 'New Mexico',
('first', 'number', 'worker', 'Oklahoma',
('any', 'base', 'both', 'South Carolina',
('nearly', 'against', 'low', 'Mississippi',
('drop', 'box', 'improve', 'Oklahoma',
('authority', 'purpose', 'hope', 'Pennsylvania',
('smile', 'southern', 'door', 'Montana',
('radio', 'media', 'letter', 'Tennessee',
('candidate', 'doctor', 'finish', 'Idaho',
('sell', 'yeah', 'sure', 'Virginia',
('find', 'determine', 'scene', 'Alaska',
('plant', 'vote', 'kid', 'Connecticut',
('available', 'debate', 'represent', 'Illinois',
('woman', 'leave', 'military', 'Massachusetts',
('plant', 'accept', 'response', 'Montana',
('white', 'itself', 'side', 'West Virginia',
('know', 'material', 'share', 'Nebraska',
('live', 'special', 'only', 'South Carolina',
('growth', 'mention', 'work', 'Kansas',
('suffer', 'what', 'level', 'Louisiana',
('follow', 'enter', 'set', 'Arizona',
('fact', 'tonight', 'bag', 'Missouri',
('cold', 'notice', 'next', 'Maine',
('item', 'policy', 'policy', 'New Mexico',
('home', 'simple', 'himself', 'Texas',
('fund', 'peace', 'attack', 'Kansas',
('surface', 'shake', 'key', 'Kansas',
('federal', 'hope', 'so', 'Idaho',
('relate', 'all', 'family', 'Alaska',
('remain', 'space', 'deep', 'Florida',
('however', 'senior', 'talk', 'South Dakota',
('court', 'high', 'fear', 'Kentucky',
('city', 'play', 'eight', 'Georgia',
('until', 'station', 'thousand', 'Indiana',
('its', 'what', 'safe', 'Rhode Island',
('tough', 'memory', 'executive', 'North Carolina',
('ask', 'call', 'Democrat', 'Vermont',
('result', 'key', 'watch', 'Maryland',
('enjoy', 'color', 'might', 'Alaska',
('citizen', 'improve', 'few', 'Utah',
('window', 'partner', 'rate', 'Georgia',
('foreign', 'already', 'type', 'Missouri',
('to', 'threat', 'court', 'Virginia',
('east', 'human', 'community', 'South Dakota',
('music', 'less', 'animal', 'Rhode Island',
('stock', 'employee', 'occur', 'Utah',
('hold', 'land', 'part', 'Missouri',
('represent', 'poor', 'begin', 'Florida',
('father', 'as', 'visit', 'Kentucky',
('break', 'expert', 'return', 'Utah',
('way', 'charge', 'song', 'Georgia',
('such', 'tonight', 'may', 'Missouri',
('strategy', 'require', 'not', 'Maine',
('surface', 'Mr', 'help', 'Wyoming',
('exactly', 'rise', 'sign', 'Delaware',
('standard', 'parent', 'wind', 'Massachusetts',
('deal', 'big', 'culture', 'Minnesota',
('continue', 'significant', 'class', 'New Mexico',
('perform', 'but', 'owner', 'California',
('culture', 'certain', 'eight', 'West Virginia',
('reality', 'science', 'around', 'New York',
('series', 'market', 'participant', 'Iowa',
('risk', 'economic', 'race', 'Florida',
('media', 'other', 'reflect', 'Louisiana',
('air', 'believe', 'rock', 'Iowa',
('song', 'draw', 'run', 'North Dakota',
('hand', 'give', 'nor', 'California',
('whatever', 'professional', 'course', 'Rhode Island',
('new', 'big', 'bed', 'New Jersey',
('sea', 'water', 'employee', 'Wisconsin',
('main', 'sense', 'Republican', 'Virginia',
('our', 'western', 'economy', 'Kentucky',
('support', 'smile', 'term', 'Massachusetts',
('discussion', 'begin', 'college', 'New Hampshire',
('sure', 'significant', 'red', 'Oklahoma',
('voice', 'best', 'operation', 'Kentucky',
('good', 'program', 'fast', 'Louisiana',
('receive', 'bar', 'seat', 'West Virginia',
('store', 'too', 'ask', 'Tennessee',
('project', 'mean', 'really', 'Missouri',
('prove', 'drive', 'rise', 'Ohio',
('difference', 'return', 'company', 'Vermont',
('fact', 'media', 'maintain', 'North Carolina',
('official', 'arrive', 'defense', 'Connecticut',
('natural', 'cell', 'newspaper', 'Hawaii',
('director', 'feel', 'us', 'Michigan',
('forward', 'in', 'place', 'Tennessee',
('total', 'rock', 'rate', 'Idaho',
('total', 'model', 'size', 'Nebraska',
('degree', 'however', 'bed', 'Pennsylvania',
('treat', 'story', 'property', 'Utah',
('upon', 'bring', 'modern', 'Connecticut',
('mother', 'possible', 'reduce', 'Colorado',
('month', 'music', 'production', 'New York',
('line', 'history', 'listen', 'Nebraska',
('keep', 'a', 'range', 'New Mexico',
('professional', 'small', 'police', 'North Carolina',
('beyond', 'past', 'her', 'Hawaii',
('stage', 'above', 'dog', 'Arizona',
('somebody', 'ball', 'animal', 'Texas',
('example', 'end', 'fast', 'Texas',
('least', 'age', 'interview', 'New Hampshire',
('whatever', 'case', 'population', 'Iowa',
('job', 'expert', 'direction', 'California',
('heavy', 'would', 'fine', 'Texas',
('meeting', 'approach', 'check', 'Virginia',
('call', 'couple', 'end', 'Massachusetts',
('top', 'place', 'scientist', 'South Carolina',
('small', 'federal', 'serious', 'Colorado',
('goal', 'positive', 'arm', 'Colorado',
('doctor', 'choose', 'probably', 'New Hampshire',
('wait', 'age', 'nice', 'Kansas',
('respond', 'structure', 'more', 'Pennsylvania',
('former', 'most', 'president', 'Delaware',
('opportunity', 'play', 'throughout', 'Connecticut',
('green', 'record', 'building', 'North Dakota',
('through', 'maintain', 'international', 'Nevada',
('respond', 'great', 'radio', 'Oregon',
('maintain', 'meeting', 'over', 'Idaho',
('also', 'majority', 'table', 'Ohio',
('than', 'personal', 'new', 'Utah',
('man', 'break', 'then', 'Florida',
('nearly', 'section', 'defense', 'Georgia',
('current', 'crime', 'main', 'Iowa',
('help', 'action', 'final', 'West Virginia',
('bill', 'admit', 'civil', 'Minnesota',
('future', 'huge', 'remain', 'New Jersey',
('fact', 'add', 'hold', 'Pennsylvania',
('without', 'draw', 'entire', 'New Hampshire',
('remain', 'others', 'degree', 'Hawaii',
('already', 'development', 'real', 'New York',
('quality', 'wonder', 'purpose', 'Florida',
('bring', 'activity', 'check', 'California',
('institution', 'somebody', 'represent', 'Illinois',
('stop', 'light', 'speech', 'Idaho',
('human', 'scientist', 'size', 'Arizona',
('court', 'offer', 'lawyer', 'Florida',
('write', 'top', 'where', 'Indiana',
('military', 'water', 'just', 'Nevada',
('treat', 'keep', 'blue', 'California',
('little', 'choice', 'one', 'New Jersey',
('community', 'citizen', 'alone', 'Iowa',
('debate', 'those', 'machine', 'New Mexico',
('water', 'six', 'federal', 'Idaho',
('sit', 'prevent', 'decide', 'New Hampshire',
('bill', 'heart', 'discuss', 'Virginia',
('benefit', 'song', 'matter', 'Maryland',
('fear', 'affect', 'chance', 'Nevada',
('upon', 'do', 'ground', 'Nevada',
('red', 'machine', 'something', 'Mississippi',
('without', 'subject', 'door', 'Ohio',
('husband', 'his', 'myself', 'Montana',
('affect', 'thank', 'plant', 'Hawaii',
('the', 'describe', 'everyone', 'South Dakota',
('get', 'meet', 'event', 'Arkansas',
('firm', 'fish', 'listen', 'Utah',
('different', 'open', 'full', 'Indiana',
('feel', 'join', 'clear', 'Kentucky',
('there', 'series', 'certain', 'Utah',
('yet', 'minute', 'order', 'Ohio',
('maybe', 'suggest', 'home', 'Ohio',
('top', 'begin', 'what', 'Oregon',
('into', 'article', 'realize', 'New Mexico',
('actually', 'rest', 'player', 'Minnesota',
('understand', 'meeting', 'spend', 'Texas',
('use', 'relationship', 'at', 'West Virginia',
('population', 'return', 'machine', 'Hawaii',
('son', 'yet', 'system', 'Colorado',
('personal', 'record', 'who', 'New Jersey',
('article', 'change', 'put', 'California',
('important', 'send', 'use', 'Maryland',
('high', 'describe', 'ago', 'Alabama',
('information', 'program', 'worker', 'Idaho',
('rule', 'whom', 'significant', 'California',
('affect', 'buy', 'white', 'California',
('want', 'heavy', 'minute', 'South Carolina',
('sense', 'reason', 'dinner', 'West Virginia',
('improve', 'enough', 'yet', 'Indiana',
('teacher', 'walk', 'wall', 'New Jersey',
('type', 'treat', 'case', 'North Carolina',
('company', 'see', 'coach', 'South Carolina',
('likely', 'customer', 'guess', 'Maine',
('chair', 'she', 'apply', 'South Carolina',
('then', 'set', 'they', 'Hawaii',
('want', 'drug', 'future', 'Georgia',
('word', 'authority', 'enter', 'Maryland',
('level', 'rather', 'share', 'Kentucky',
('nearly', 'man', 'if', 'North Dakota',
('go', 'near', 'beyond', 'Georgia',
('president', 'turn', 'town', 'Oregon',
('mouth', 'various', 'time', 'Maine',
('effort', 'system', 'former', 'West Virginia',
('business', 'once', 'vote', 'Vermont',
('keep', 'team', 'lose', 'Kansas',
('front', 'identify', 'according', 'Washington',
('show', 'best', 'away', 'Delaware',
('well', 'small', 'seven', 'Alabama',
('spring', 'citizen', 'father', 'New York',
('you', 'event', 'week', 'Washington',
('middle', 'information', 'event', 'Alabama',
('for', 'class', 'election', 'Arkansas',
('always', 'best', 'debate', 'Massachusetts',
('response', 'voice', 'police', 'Missouri',
('compare', 'catch', 'listen', 'Michigan',
('newspaper', 'recognize', 'bag', 'California',
('current', 'professional', 'respond', 'New Hampshire',
('stage', 'high', 'particular', 'Oregon',
('newspaper', 'game', 'within', 'North Dakota',
('me', 'another', 'throw', 'Vermont',
('thing', 'add', 'citizen', 'Connecticut',
('generation', 'think', 'whose', 'Illinois',
('visit', 'next', 'participant', 'Alabama',
('determine', 'act', 'table', 'Nebraska',
('collection', 'measure', 'particularly', 'New Jersey',
('difficult', 'along', 'anyone', 'Maryland',
('world', 'red', 'report', 'Montana',
('card', 'strategy', 'share', 'Texas',
('financial', 'language', 'list', 'North Dakota',
('rich', 'policy', 'fill', 'Florida',
('public', 'free', 'director', 'New Hampshire',
('girl', 'actually', 'month', 'Connecticut',
('town', 'free', 'almost', 'Nevada',
('my', 'help', 'amount', 'New York',
('mission', 'consumer', 'agree', 'Georgia',
('parent', 'police', 'bad', 'South Carolina',
('challenge', 'statement', 'act', 'Connecticut',
('meet', 'enjoy', 'free', 'Oklahoma',
('accept', 'wish', 'hot', 'Arizona',
('amount', 'several', 'since', 'Kentucky',
('add', 'see', 'stuff', 'Montana',
('magazine', 'cup', 'pull', 'Oklahoma',
('affect', 'exactly', 'everybody', 'Delaware',
('choice', 'these', 'per', 'Louisiana',
('billion', 'onto', 'remain', 'Louisiana',
('seem', 'letter', 'year', 'Colorado',
('treat', 'discussion', 'large', 'Nebraska',
('her', 'beyond', 'window', 'Washington',
('think', 'for', 'somebody', 'Arkansas',
('stage', 'nearly', 'my', 'Massachusetts',
('glass', 'school', 'mind', 'Wisconsin',
('southern', 'today', 'all', 'Nebraska',
('leave', 'soon', 'water', 'Connecticut',
('nation', 'news', 'commercial', 'North Dakota',
('no', 'computer', 'structure', 'Wisconsin',
('yourself', 'right', 'throw', 'Maine',
('throw', 'speech', 'everybody', 'Wisconsin',
('certainly', 'turn', 'piece', 'Oklahoma',
('a', 'million', 'couple', 'New Mexico',
('lawyer', 'position', 'need', 'Utah',
('want', 'middle', 'PM', 'Pennsylvania',
('travel', 'pick', 'specific', 'New Hampshire',
('station', 'not', 'term', 'New Jersey',
('money', 'yet', 'task', 'Maine',
('thing', 'current', 'return', 'West Virginia',
('street', 'skin', 'why', 'Minnesota',
('price', 'summer', 'interesting', 'Indiana',
('decision', 'establish', 'somebody', 'New York',
('popular', 'point', 'official', 'Maryland',
('system', 'not', 'heavy', 'Iowa',
('road', 'president', 'study', 'Colorado',
('arm', 'yard', 'thousand', 'Alabama',
('determine', 'arrive', 'issue', 'New Mexico',
('and', 'note', 'guy', 'Alaska');