INSERT INTO cities_population (area, city, country, population)
VALUES ('then', 'Melindashire', 'power', 'suffer',
('sometimes', 'Smithberg', 'at', 'represent',
('shoulder', 'Wernerchester', 'fish', 'party',
('by', 'Brendaton', 'decide', 'hit',
('cause', 'South Allison', 'land', 'beat',
('movie', 'East Brandi', 'similar', 'material',
('trade', 'West Cheryl', 'most', 'course',
('writer', 'Port Kristinview', 'score', 'mind',
('individual', 'Pattersonhaven', 'suddenly', 'tax',
('positive', 'Lake Jeffreystad', 'conference', 'season',
('at', 'South Erin', 'participant', 'seem',
('coach', 'North Justin', 'coach', 'work',
('consider', 'Port Vanessashire', 'use', 'stuff',
('sport', 'Thomasbury', 'generation', 'environment',
('bank', 'Debrabury', 'certainly', 'check',
('smile', 'Stephanieview', 'no', 'behavior',
('sea', 'North Timothy', 'trouble', 'I',
('however', 'Dustinborough', 'energy', 'interview',
('live', 'North Christopherfurt', 'believe', 'relate',
('dinner', 'East Derrick', 'such', 'world',
('throw', 'Raymondtown', 'west', 'far',
('majority', 'Williamston', 'study', 'and',
('tonight', 'West Victoria', 'rate', 'two',
('care', 'New Michaelburgh', 'few', 'before',
('upon', 'Armstrongton', 'special', 'personal',
('employee', 'Lake Amanda', 'loss', 'amount',
('cause', 'Edwardsmouth', 'collection', 'not',
('sign', 'Port Sherri', 'what', 'fire',
('offer', 'Davidfort', 'job', 'worry',
('fast', 'Roweberg', 'really', 'apply',
('produce', 'Smithton', 'road', 'million',
('in', 'Millerstad', 'happy', 'mouth',
('since', 'Port Michael', 'now', 'interesting',
('they', 'Port Lauren', 'hot', 'agent',
('wait', 'South Travismouth', 'something', 'investment',
('lay', 'North Matthewfort', 'magazine', 'meet',
('bag', 'Jasonport', 'reveal', 'three',
('easy', 'Port Amber', 'air', 'meeting',
('likely', 'West Krystal', 'former', 'true',
('role', 'Palmerbury', 'market', 'without',
('report', 'Vazquezland', 'figure', 'listen',
('Republican', 'Shirleyburgh', 'shoulder', 'century',
('teacher', 'Barkerstad', 'receive', 'race',
('set', 'Hunterchester', 'four', 'as',
('indicate', 'Toddburgh', 'me', 'assume',
('tough', 'Port Carltown', 'nothing', 'attention',
('former', 'New Oliviaside', 'lead', 'two',
('PM', 'Dodsonbury', 'someone', 'strategy',
('off', 'Brownmouth', 'guess', 'information',
('order', 'Port Hannah', 'television', 'east',
('thank', 'North Christopher', 'popular', 'rate',
('gun', 'Alexisshire', 'probably', 'light',
('program', 'Harrisonstad', 'bit', 'positive',
('hundred', 'Christyfurt', 'prepare', 'voice',
('mean', 'Port Jeremyshire', 'huge', 'maybe',
('understand', 'East Ariel', 'nation', 'let',
('media', 'Lake Erica', 'fine', 'business',
('late', 'Lake Lisa', 'would', 'state',
('by', 'South Theresaport', 'direction', 'realize',
('fact', 'Wellston', 'Mrs', 'government',
('them', 'Port Matthew', 'material', 'some',
('dinner', 'Mirandaside', 'big', 'perhaps',
('now', 'Lake Jasonberg', 'work', 'politics',
('almost', 'East Gabrielville', 'behind', 'certainly',
('always', 'Melindaside', 'draw', 'hold',
('check', 'New Bryanburgh', 'leg', 'course',
('radio', 'West Anthonyborough', 'thought', 'capital',
('party', 'Murphyland', 'people', 'him',
('experience', 'Juliatown', 'action', 'organization',
('day', 'Matthewbury', 'until', 'college',
('school', 'Espinozaborough', 'daughter', 'father',
('determine', 'Stephenstown', 'outside', 'reduce',
('smile', 'Pamstad', 'thousand', 'something',
('while', 'South Diana', 'western', 'policy',
('energy', 'North Nicole', 'nation', 'usually',
('short', 'Nguyenport', 'else', 'appear',
('build', 'South Nicoleburgh', 'manage', 'attack',
('attorney', 'West James', 'factor', 'around',
('seven', 'Port Hollyview', 'wall', 'job',
('get', 'Lake Yvonneport', 'land', 'authority',
('most', 'Phillipburgh', 'perhaps', 'call',
('church', 'Leehaven', 'perhaps', 'nature',
('page', 'Greenechester', 'minute', 'church',
('never', 'North Victor', 'standard', 'maybe',
('move', 'New Shane', 'bill', 'generation',
('action', 'Danamouth', 'agency', 'car',
('begin', 'Georgemouth', 'reason', 'investment',
('add', 'New Matthewland', 'wife', 'have',
('over', 'Port Martin', 'friend', 'month',
('establish', 'Lake Patricia', 'none', 'more',
('just', 'Vegaview', 'several', 'option',
('top', 'North Mistymouth', 'number', 'property',
('oil', 'North Andrew', 'word', 'money',
('check', 'Martinhaven', 'year', 'TV',
('fast', 'North Joseph', 'general', 'sort',
('art', 'South Jacob', 'task', 'face',
('radio', 'West Trevor', 'before', 'measure',
('box', 'Clarkshire', 'ahead', 'until',
('eye', 'North Melindahaven', 'apply', 'reflect',
('central', 'Williamton', 'identify', 'personal',
('send', 'Donnaberg', 'take', 'dinner',
('goal', 'Thompsonshire', 'head', 'front',
('your', 'Gravesberg', 'three', 'whom',
('the', 'Port Garyfurt', 'lose', 'station',
('worry', 'Rodriguezshire', 'she', 'travel',
('ready', 'Lake Michelleton', 'trial', 'poor',
('three', 'Jadeton', 'old', 'huge',
('worry', 'Marissaland', 'word', 'true',
('feeling', 'Lake Lauriehaven', 'them', 'choose',
('new', 'South Brianbury', 'letter', 'than',
('dog', 'West Jamieport', 'shake', 'everyone',
('process', 'Lake Gregoryton', 'perform', 'once',
('last', 'East Travis', 'sea', 'summer',
('fine', 'East Michaelfort', 'under', 'nation',
('article', 'North Melissaborough', 'decade', 'interest',
('growth', 'East Alyssa', 'trial', 'another',
('either', 'Tammyland', 'himself', 'money',
('which', 'East Steven', 'star', 'when',
('adult', 'East Tracyfurt', 'report', 'decide',
('game', 'Owensport', 'or', 'along',
('down', 'Samuelbury', 'I', 'each',
('machine', 'Brownchester', 'country', 'at',
('dinner', 'Allenborough', 'country', 'political',
('company', 'East Anita', 'answer', 'character',
('yet', 'Emilytown', 'arrive', 'around',
('decide', 'North Tina', 'late', 'young',
('reason', 'New Briana', 'show', 'conference',
('too', 'Rodriguezchester', 'last', 'wonder',
('themselves', 'Turnerton', 'successful', 'rate',
('yeah', 'Costatown', 'choice', 'he',
('policy', 'Port Jennifer', 'old', 'everyone',
('cause', 'South David', 'memory', 'future',
('gas', 'East Matthew', 'relate', 'course',
('pretty', 'Karenfurt', 'set', 'pass',
('form', 'Patrickburgh', 'figure', 'others',
('before', 'New Terry', 'speech', 'direction',
('range', 'Jessicaborough', 'respond', 'service',
('others', 'South Mikaylafurt', 'economic', 'religious',
('dream', 'Port James', 'region', 'onto',
('area', 'East Rebeccamouth', 'loss', 'car',
('must', 'East Jorgeton', 'sing', 'wish',
('issue', 'Anitaland', 'where', 'watch',
('magazine', 'Robinhaven', 'authority', 'hold',
('quickly', 'Pricestad', 'treatment', 'central',
('the', 'Lake Richardmouth', 'work', 'charge',
('edge', 'Port Lindsey', 'clearly', 'or',
('enough', 'West Tiffany', 'indeed', 'fire',
('care', 'Elizabethtown', 'can', 'ability',
('seven', 'Georgeside', 'miss', 'arrive',
('poor', 'East Lisamouth', 'she', 'value',
('author', 'Lake Sandra', 'record', 'test',
('hard', 'East Barbarafort', 'team', 'move',
('already', 'Beckermouth', 'particular', 'culture',
('stand', 'New Nancy', 'expert', 'under',
('beyond', 'West Brian', 'store', 'investment',
('page', 'Angelaview', 'rest', 'easy',
('suggest', 'West Andrewshire', 'low', 'floor',
('executive', 'West Amandafurt', 'discussion', 'fund',
('similar', 'North Erinchester', 'record', 'mind',
('but', 'Denisemouth', 'laugh', 'another',
('rate', 'Joshuaport', 'child', 'important',
('term', 'North Jason', 'realize', 'sort',
('address', 'North Emily', 'rather', 'training',
('ability', 'Erikbury', 'various', 'nice',
('without', 'Port Tiffany', 'field', 'vote',
('case', 'East Michaelshire', 'usually', 'reflect',
('newspaper', 'Donaldsonview', 'reduce', 'professor',
('information', 'East Elizabethborough', 'production', 'few',
('medical', 'South Kylehaven', 'I', 'hospital',
('fill', 'Williston', 'speak', 'especially',
('character', 'Spearsborough', 'small', 'different',
('subject', 'Jessemouth', 'business', 'bill',
('office', 'Sharpburgh', 'sense', 'series',
('know', 'South Benjaminchester', 'manager', 'law',
('single', 'Johnsonville', 'lose', 'capital',
('scientist', 'Lake Carolland', 'impact', 'until',
('voice', 'Evanstad', 'gas', 'defense',
('tough', 'North Marisaberg', 'effort', 'blood',
('city', 'New Wesley', 'plan', 'north',
('thank', 'Horneshire', 'like', 'me',
('skin', 'Gregoryshire', 'probably', 'something',
('current', 'Sheaborough', 'stock', 'break',
('during', 'Wongfort', 'fine', 'reason',
('various', 'Chavezhaven', 'cut', 'blue',
('response', 'Vickiberg', 'build', 'north',
('human', 'East Kathleenmouth', 'morning', 'child',
('style', 'South Levi', 'last', 'better',
('interest', 'East Kevinshire', 'cause', 'floor',
('air', 'Stonehaven', 'five', 'cover',
('anything', 'West Gary', 'woman', 'spend',
('present', 'Tinaberg', 'seek', 'yard',
('officer', 'Port Sonyamouth', 'director', 'choice',
('wonder', 'Farmershire', 'fly', 'son',
('institution', 'Muellermouth', 'six', 'every',
('rest', 'West Jesse', 'gun', 'first',
('recognize', 'New Devintown', 'sometimes', 'story',
('store', 'Floresview', 'tell', 'commercial',
('computer', 'Williamsshire', 'debate', 'main',
('involve', 'Gilbertshire', 'story', 'suggest',
('produce', 'Meyerland', 'yeah', 'support',
('stand', 'Port Elizabethfort', 'miss', 'fast',
('they', 'Hurstfort', 'end', 'the',
('position', 'Dianeside', 'foreign', 'represent',
('medical', 'Amymouth', 'phone', 'follow',
('purpose', 'East Heather', 'room', 'decade',
('truth', 'Suttonchester', 'all', 'itself',
('itself', 'Wellsstad', 'happy', 'quickly',
('pull', 'Thorntonberg', 'good', 'lot',
('college', 'Amandaborough', 'class', 'subject',
('family', 'Zoehaven', 'some', 'citizen',
('level', 'Lake Karen', 'successful', 'piece',
('picture', 'South Jonathontown', 'back', 'beat',
('nor', 'Lisamouth', 'direction', 'foreign',
('prove', 'South Michael', 'various', 'chance',
('large', 'Millerburgh', 'season', 'answer',
('clear', 'Port Victoria', 'compare', 'spring',
('pull', 'Lake Thomas', 'off', 'finally',
('available', 'Lauriestad', 'law', 'play',
('evidence', 'Ashleyborough', 'technology', 'could',
('six', 'Davidbury', 'choose', 'human',
('series', 'Davidfurt', 'anyone', 'shoulder',
('short', 'Benjaminbury', 'sound', 'water',
('religious', 'Mitchellport', 'beautiful', 'discussion',
('expect', 'Arielborough', 'debate', 'very',
('fire', 'Shannonburgh', 'dinner', 'thus',
('car', 'Joshuaville', 'early', 'agent',
('region', 'Sharpchester', 'official', 'change',
('thousand', 'Thomasmouth', 'shake', 'yes',
('either', 'Klineshire', 'forget', 'six',
('prevent', 'Jennifermouth', 'sense', 'modern',
('it', 'Klinebury', 'century', 'season',
('put', 'New Willie', 'seem', 'improve',
('material', 'Lopezside', 'same', 'choice',
('hear', 'Lake Julieberg', 'article', 'throw',
('authority', 'Estesborough', 'environmental', 'media',
('loss', 'Port Josephtown', 'drive', 'vote',
('throughout', 'Kimfurt', 'hold', 'despite',
('show', 'New Jared', 'report', 'front',
('Democrat', 'New Jeffreystad', 'southern', 'resource',
('plan', 'Landryville', 'build', 'travel',
('per', 'East Laura', 'direction', 'game',
('blue', 'New Henry', 'sport', 'guy',
('source', 'Port Jeffreyberg', 'concern', 'give',
('economy', 'South Robert', 'foot', 'owner',
('matter', 'Patrickport', 'major', 'cut',
('final', 'New Darrell', 'cut', 'hard',
('many', 'East Michael', 'seem', 'guy',
('likely', 'Jeffreyborough', 'owner', 'concern',
('put', 'Timothyburgh', 'almost', 'general',
('pick', 'Lake David', 'reflect', 'about',
('us', 'South Billy', 'Republican', 'program',
('system', 'Figueroastad', 'worry', 'recently',
('deal', 'Aprilberg', 'truth', 'such',
('great', 'Brittanyland', 'police', 'purpose',
('exactly', 'Susanstad', 'list', 'recent',
('garden', 'Lake Jamie', 'former', 'certainly',
('discuss', 'Aaronborough', 'speak', 'federal',
('listen', 'Lake James', 'system', 'thousand',
('animal', 'Michaelville', 'tell', 'every',
('father', 'North Bethmouth', 'side', 'lay',
('between', 'Mitchellmouth', 'difference', 'clear',
('market', 'South James', 'despite', 'laugh',
('PM', 'South Amandaland', 'necessary', 'compare',
('star', 'Port Robert', 'floor', 'different',
('enter', 'East Parker', 'window', 'create',
('man', 'North Cynthiashire', 'population', 'too',
('another', 'New Rachel', 'assume', 'cold',
('wind', 'Lake Mikeland', 'small', 'south',
('can', 'West Catherine', 'again', 'song',
('TV', 'Hamiltonfurt', 'have', 'always',
('two', 'Port Mollytown', 'job', 'long',
('focus', 'West Christinashire', 'worker', 'five',
('choose', 'Hunttown', 'matter', 'company',
('Democrat', 'North Traceyport', 'seem', 'create',
('great', 'Wagnerbury', 'letter', 'part',
('government', 'Baileyside', 'trip', 'same',
('those', 'Port Mary', 'together', 'increase',
('cup', 'East Garrettland', 'final', 'expect',
('area', 'Allenside', 'later', 'collection',
('son', 'East Cheryl', 'democratic', 'college',
('son', 'Howardview', 'low', 'peace',
('culture', 'East Robert', 'language', 'modern',
('until', 'North Edwardland', 'ability', 'item',
('war', 'Blevinsshire', 'goal', 'indeed',
('fact', 'Villegasfurt', 'key', 'ability',
('decide', 'East Robert', 'indicate', 'two',
('professor', 'Leestad', 'item', 'Mr',
('month', 'West Tina', 'unit', 'study',
('sport', 'East Bethville', 'thought', 'serve',
('specific', 'Anthonyfort', 'then', 'order',
('matter', 'Frankville', 'performance', 'brother',
('someone', 'Lake Mary', 'much', 'though',
('difficult', 'South Anthonyside', 'over', 'position',
('system', 'South Nicoleburgh', 'country', 'decide',
('television', 'Ricemouth', 'store', 'another',
('camera', 'Lake Shaneborough', 'food', 'quickly',
('report', 'Lake Patrick', 'rule', 'citizen',
('phone', 'Frankborough', 'forward', 'heart',
('open', 'Padillaton', 'effort', 'reality',
('herself', 'Samanthaville', 'foot', 'agree');